### ISSUE TITLE
Wox won't start

### ISSUE THREAD

**Issue by mavanmanen** [Wox-launcher/Wox#1002]
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version / commit number: 1.3.297
2. Steps to **reproduce** the bug: Starting wox
3. Windows version: Windows 10 Insider Preview 14936
4. Exception:  
   `2016-10-02 23:17:49.4857|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:`  
   `2016-10-02 23:17:49.5235|ERROR|Shell.IShellLinkW.GetDescription|Error HRESULT E_FAIL has been returned from a call to a COM component.`
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`): [https://gist.github.com/mavanmanen/e702bbfb71223d088d5cb3d1426ec63c](https://gist.github.com/mavanmanen/e702bbfb71223d088d5cb3d1426ec63c)
6. Screenshot (optional):

**Comment by lances101** [comment]
@mavanmanen, hey there. Due to you being on an insider preview build it's harder for any of us to debug it. It also doesn't help that the error returned is HRESULT's `E_FAIL` [which corresponds to](https://msdn.microsoft.com/en-us/library/cc704587.aspx)`Unspecified error.` which technically could be anything. I suppose that MS changed something related to ShellLink handling. The build is also like 4 days old so even if the problem is really there it may take at least a week for information to start popping up.

I am pretty sure this is not an issue with Wox itself. Fastest way to check this is to throw together a small app that uses the same COM component. 

Maybe somebody has other ideas about your issue, but from my point of view there is very little we can do.

**Comment by mavanmanen** [comment]
Manually stepping through code I've tracked it down to:  
`at Shell.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cch)  
at Wox.Plugin.Program.Programs.Win32.LnkProgram(String path) in D:\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 157`

**Comment by bao-qian** [comment]
hi
those exception won't prevent you startup,
please upload the **whole** log file
