### ISSUE TITLE
Option "Hide Wox on startup" not working

### ISSUE THREAD

**Issue by HA3IK** [Wox-launcher/Wox#1009]
1. v1.3.183 #0300bb5
2. Selected option "Hide Wox on startup". Restart Windows. Wox is displayed when Windows 10 was started
3. Windows 10 _(Not Insider Preview. With all latest updates)_
4. -
5. -
6. [Screenshot](https://d.pr/1aSmY)

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/x48xfu93b8jq2fir/artifacts/Releases%2FWox-1.3.297.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

This may not fix the issue, but its the best I can do for now. Once you confirm that the issue is still present, we will try to figure something out. I just cannot replicate it on my machine with that build.

**Comment by HA3IK** [comment]
Version 1.3.297 solved this problem thanks.

**Comment by bao-qian** [comment]
duplicate #1016
