### ISSUE TITLE
bugs about blank action key

### ISSUE THREAD

**Issue by AmoseKang** [Wox-launcher/Wox#1024]
## how to

 change an action key of a plugin to blank (type nothing and press `done`)
## what happened

 everything you typed will **only** trigger the plugin
 you can't change it back because there is no linked text to click again
 _i tried to change `AppData\\Roaming\\Wox\\Settings\\Settings.json` but didn't work (not sure)_
### e.g.

   i change the action key for package installer 
   then whatever i typed in search bar will only show infomation about installing package
## info
- program version 1.3.183
- windows version 10.0.14393

**Comment by lances101** [comment]
Oh my, it really does happen. I thought we had a check for that. To change an action of a plugin to `blank` (as in "fire for any query") you should use `*`. 

As for a fix for you right now, try the following:
- close Wox via the tray icon
- go to `C:\Users\<username>\AppData\Roaming\Wox\Settings\` 
- open `Settings.json` with an editor of your choice
- find the entry (ctrl+f, for example) with the plugin that you changed the hotkey to `blank`.  You will be presented with something like this

```
"0ECADE17459B49F587BF81DC3A125110": {
        "ID": "0ECADE17459B49F587BF81DC3A125110",
        "Name": "Browser Bookmarks",
        "ActionKeywords": [
          ""
        ],
        "Disabled": false
      },
```

Add a letter of your choice at `"ActionKeywords": [ "" ],` so that it ends up looking like  this `"ActionKeywords": [ "b" ],`. That's should do it.  Start Wox.

**Comment by lances101** [comment]
Fixed as of https://github.com/Wox-launcher/Wox/commit/83282ebcb8f27bdb05c81059511c4254923b0d2d

Closed.
