### ISSUE TITLE
Wox python module

### ISSUE THREAD

**Issue by jrock2004** [Wox-launcher/Wox#1046]
I want to do some local plugin development and I want to debug my code. Where can I get the wox python module so my app can see it? Can I pip install it?

**Comment by lances101** [comment]
@jrock2004 hey there. 

You can find an example Python plugin in the plugins folder of your Wox installation. 
You can open that folder either by opening Wox's settings window, going to the plugin tab, finding `Hello World Python` in the plugins list and clicking "Plugin Directory" in the upper right or just going to the following path

`C:\Users\<username>\AppData\Local\Wox\<wox_version>\Plugins\HelloWorldPython`

**Comment by jrock2004** [comment]
Maybe I should probably have reworded this better. I am using Visual Studio code and I want to debug when the code is being executed. 

![image](https://cloud.githubusercontent.com/assets/655716/20107548/e42bdb44-a5a6-11e6-9848-b8173fccf635.png)

**Comment by lances101** [comment]
I didn't think I would be able to answer your question in a positive way, but it seems like it is possible! 

[Discovered that VSCode python debugging is possible by stumbling upon this.](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging)

[Here is the HelloWorldPython example](http://lances101.github.io/storage/HelloWorldPython.zip) with the added lines for debugging. I've added comments explaining what does what.

What you need to do:
- Replace the contents of the `HelloWorldPython` plugin with the ones in the archive. Open Wox's settings and set the python path. **Restart Wox**.
- run `pip install ptvsd`
- open VSCode with the `HelloWorldPython` directory as your workspace. Take a look into launch.json. I've added a configuration for remote debugging.
- open the debug tab, set the configuration to `Python Attach`

At this point you are all setup. Now toggle wox, type `h` (it's the default keyword for the plugin) and in VSCode hit F5 (or press debug). You have 5 seconds to do this. You can change the amount of time the script waits for the debugger by changing the parameter on line 22 of the main.py. 

Everything seems to work **except for breakpoints**. You need to force the first breakpoint with `ptvsd.break_into_debugger`. After that they seem to work fine. 

**Edit** if the debugger stops attaching it's possible that it is because of multiple instances of the plugin execution are listening. I guess inside of the block that attaches we could force attach the running plugin to kill off any other instance listening for a debugger. As a workaround try killing `pythonw.exe` instances.

![image](https://cloud.githubusercontent.com/assets/4784785/20112950/a307ee1c-a5ee-11e6-930d-a59183d05fe8.png)

**Comment by VVinRar** [comment]
Hello there!
Followed your instructions, but I have not success. No debugging occurs, the pythonw.exe shown in proccess for 5 seconds and then exits. I tried different versions ptvsd (3.0, 2.0). The connection to debugging itself does not occur for some reason.
Can you please help me??

**Comment by avionbg** [comment]
You should try with python.exe, not sure if it works with pythonw. And it's like lances101 explained. I just installed 32bit python 3.7 (latest from their site). Installed without launcher, put it in c:/python37-32 and updated the path to python inside wox settings. Vscode should have right interpreter selected (in case you have more than one python installed) and it just works. Mind that you need to restart Wox after changing the plugin code!

**Comment by VVinRar** [comment]
Thx 4 answer
Here is my work setup from launch.json:
`        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            // "secret": "secret1",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        },
`
This works for me
