### ISSUE TITLE
Is it possible to have a smaller theme? 

### ISSUE THREAD

**Issue by Remiol** [Wox-launcher/Wox#1054]
All the themes use 50% of my screen width.
I used a very small theme of launchy before.

Is it possible to make the width of the themes smaller?
20% of my screen or even smaller?

**Comment by lances101** [comment]
@Remiol You can change the themes yourself. You can find them in the Themes folder of the Wox installation. 

I've made a small version of the pink theme for you as an example. Put in the Themes folder, close and open the Settings window and choose it. It will change the size of the window as well as fonts. You can edit the theme by opening it with a text editor and tweaking the values. 

P.S. You may notice that choosing bigger themes does not change the size of Wox after using this theme. This is because they don't have a size defined. If you want to use a theme that does not have a size defined - restart Wox to reset the max size. 

[Pink Mini.xaml.zip](https://github.com/Wox-launcher/Wox/files/578541/Pink.Mini.xaml.zip)

**Comment by Remiol** [comment]
Very kind of you that you've created this smaller theme. Thank you very much but I've decided to uninstall the software. I had not less then 10 crashes since I installed Wox 2 days ago. Plugins (translate, google translate, wox switcher). All crashed. Switching theme yesterday (before to install your pink theme) crashed Wox (and after having installed Wox from scratch without plugins). I installed your pink theme one hour ago and it crashed also. When I restarted Wox (after removing the pink theme) I could use the program without problems. Then I decided to create my own theme online (http://www.getwox.com/theme/builder) downloaded the theme and saved it in the theme directory, and it crashed again after a while. I think the software is not stable enough. However I like it very much. Don't understand why there is no way to uninstall plugins. Tried also the Clipboard history plugin but I could not remove the clipboard history. Too many things don't go well. I will keep an eye on your updates and will try it again. Sorry that I won't send you all the log files of the bugs. There are too much.

**Comment by Remiol** [comment]
and forgot to write you that there is no uninstall link in Start menu. Uninstalled the software using Control Panel/Programs and Features. Uninstalled but the Wox folders are still there in Roaming and there were 3 more Wox directories on my disk. Too many things just don't work.

**Comment by lances101** [comment]
@Remiol I'm sorry you didn't have a pleasant experience. The version we have currently tagged as release (1.3.183) indeed does have some issues. In a different issue I linked you a later build that is more stable. [(here it is again in case you decide to give it a try)](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 

Regarding translation plugins, the plugin `Google Translate` usually works without any issues unless google itself denies you access (which can sometimes happen on public networks due to it not using the official api). 

Clipboard history plugin indeed does not have support for deleting entries. 

I don't know how you were actually installing plugins, but the recommended way is to use the command `wpm install` and the same goes for uninstallation (`wox uninstall`). 

Uninstalling Wox is indeed only possible through the control panel. This is something that has to be added, but as you may understand is not that high of a priority. 

Thank you for your feedback, maybe one day you will give Wox another try :)

**Comment by Remiol** [comment]
Thank you for your kind answer. I'll try it again if the errors are gone.
