### ISSUE TITLE
[question] Order of most commonly searched for programs in list

### ISSUE THREAD

**Issue by lehasb** [Wox-launcher/Wox#1162]
Not necessarily a bug, just a question about something that behaves differently than I expect. I used Launchy for years, and it would put the program I usually selected with a given search term at the top of the list. For instance, if I typed "gm" I would get Gmail, and if I typed "al" I would get Alpine. With Wox, if I type "al" I get Gmail in the results first, and then Alpine.

I think this is because I use Gmail more often, so Wox sorts it to the top of the list automatically, even though it isn't the result I want for that search term. Is there any way to change that, or is it just the way Wox is built and can't really be modified without a lot of work?

**Comment by lances101** [comment]
Wox does weighting of results based on fuzzy matching as well as the frequency of you actually choosing that result. You can also type `al`, select "Alpine" in the results list, hit `Shift+Enter` or right click the result in order to open the contextual menu. There you can choose to set it as the "topmost result". 

Once that is done every time you type in "al" it will get a higher score and therefore be first in the list. Let me know how it goes.

**Comment by lehasb** [comment]
Thanks! I had missed the "topmost result" option in the contextual menu, and using that helps a lot.
