### ISSUE TITLE
Any Updates? No more?

### ISSUE THREAD

**Issue by nrllh** [Wox-launcher/Wox#1167]
won't you update the software anymore? Last update was about 6 months ago?

**Comment by davidszp** [comment]
Bugs are not getting fixed, no more releases it seems. Sad to see, this launcher was awesome.

**Comment by lances101** [comment]
I cannot speak for @happlebao, but I'm having trouble combining work and my master thesis. The current state of the master branch is close to being a release version that is much needed because it fixes most of the issues that people are having. 

As for release frequency, an option would be to make automated releases with Appveyor, maybe add an option to autoupdate to the current dev version in Wox. But that requires writing a ton of tests and that is also time.

The plugin backend also needs some attention and hopefully from somebody with experience in Django and Angular.

**Comment by bao-qian** [comment]
new release this month
biggest feature should be uwp support. already done: #198
#977 probably be added also
if you can't wait, then https://ci.appveyor.com/project/happlebao/wox/build/1.3.325

**Comment by sustain86** [comment]
请问在新的版本中启动太慢的问题有修复吗？

**Comment by bao-qian** [comment]
@sustain86 不知道你具体指什么问题 不过你试一下吧

**Comment by sustain86** [comment]
就是启动的时候需要3 ~4分钟，感觉太慢失去快速启动器的意义。
wox版本：1.3.183
windows版本:1607

**Comment by bao-qian** [comment]
@sustain86 如果你指的是wox的启动时间，那应该在几秒之内。你需要另外开 issue，并附上 log。然后装 https://ci.appveyor.com/project/happlebao/wox/build/1.3.325， 再附上新的 log。

**Comment by bao-qian** [comment]
I think all questions has been answered, so the issue will be closed.
