### ISSUE TITLE
Cursor moves to the very right of the text

### ISSUE THREAD

**Issue by rogino** [Wox-launcher/Wox#1202]
On Wox version 1.3.183 and Windows 10 Build 14393, the cursor is on the left. After moving the cursor right to some other text and entering a key, the cursor moves to the very left of the text. This is not a problem when simply typing, but when you need to correct or edit the text, it becomes a problem. A screen recording is attached.
![wox](https://cloud.githubusercontent.com/assets/19989743/22093643/4e8a1f34-de6c-11e6-89ff-fa081be3871c.gif)

**Comment by rissson** [comment]
Same here
Wox 1.3.183 and Windows 10 Version 1607 Build 14393.693

**Comment by duianto** [comment]
This doesn't happen for me in build 1.3.295 (i've used it without any problems since sept 25), i just installed the latest build 1.3.336 and it doesn't happen there either.

The cursor stays where one would expect it, without jumping to the end when something is added or removed.

Windows 10 Version 1607 (OS Build 14393.693)

This seems to be the url to the latest build:
https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Comment by rogino** [comment]
The bug seems to be fixed in the provided build. Thanks.

**Comment by bao-qian** [comment]
#813
