### ISSUE TITLE
计算器结果无法复制到剪贴板

### ISSUE THREAD

**Issue by FlyingRadish** [Wox-launcher/Wox#1204]
例如：输入"20/2"后回车，显示“Copy failed, please try again later”

环境：Win10

**Comment by jhdxr** [comment]
这个没办法，有时候剪贴板可能被别的占用了，win的api只能做到多试几次（实际上现在也是这么做的），再出错就只能告诉用户了。。。

**Comment by bao-qian** [comment]
无解。。

**Comment by imeilige** [comment]
虽然提示Copy failed，但实际上已经复制到剪贴板了。

win10 1.3.183

**Comment by FlyingRadish** [comment]
我最后发现python实现复制到剪贴板非常稳定，所以用了python版的计算器。自己写Wox插件也都用python写了

**Comment by nianwu** [comment]
我的是因为迅雷监听剪切板，把迅雷就没问题了。

**Comment by Zhuoy3** [comment]
I encountered the same problem, and I got inspiration from https://github.com/Wox-launcher/Wox/issues/2469#issuecomment-935757046, because I enabled the flow function of Logitech Option+ similar to the Unbounded Mouse, and after turning it off, I confirmed that the behavior of copying to the clipboard returned to normal. Maybe any similar function will cause the error. Wox seems to have no intention of fixing this error in version 1.x

我遇到了相同的问题，我从 https://github.com/Wox-launcher/Wox/issues/2469#issuecomment-935757046 得到了灵感，因为我启动了类似于无界鼠标的罗技option+的flow功能，在关闭后我确认复制到剪切板的行为恢复了正常，也许任何类似的功能都会导致错误。wox似乎无意在1.x版本修复这个错误
