### ISSUE TITLE
Feature Request: multilingual search

### ISSUE THREAD

**Issue by fareloz** [Wox-launcher/Wox#1378]
A lot of people are using several languages in the system. E.g. Russian as local speaking lang and English as global and system lang to name files, write cmd commands etc. Most of the time the speaking lang is used, so it is frustrating to switch language back and forward to do English queries in WOX. 
Frequent case is when you starting to type on current language, understand that it's the wrong one, switch to another and retype.
Would request to have multilingual search in WOX - show all entries on current and other system languages by mapping query letters.
Example:
Original typed-in query: "йцукен"
Mapped to english query: "qwerty"

**Comment by arqex** [comment]
+1 for that. In my case I have my pc in Spanish, and I am having problems with tildes. For example, an application for the camera in spanish is called:

Cámara

Can you see the á? If I search for Camara I never find it. I don't know how the indexing is working but if it could treat a and á like the same character would be a great improvement.

**Comment by fareloz** [comment]
The case for "Cámara" is more complicated. It requires fuzzy search, not just simple mapping of keyboard from one lang to another.

**Comment by lances101** [comment]
@fareloz we already use fuzzy search. 
![image](https://cloud.githubusercontent.com/assets/4784785/26276051/49488346-3d6f-11e7-9abe-53b4a86f5456.png)

As for mapping different keyboard layouts to English, it is definitely an option. I will mark this issue as a suggested feature. I do not have the time to implement this right now, but maybe somebody will pick this up.

**Comment by fareloz** [comment]
@lances101 Great news! Thank you

**Comment by bao-qian** [comment]
this has already been implemented for chinese pinyin.
since I don't know Russian or Spanish, this feature need help from other people.

**Comment by bao-qian** [comment]
@arqex @fareloz 

I don't know Spanish or Russian, could you give a keyboard map from your local language (Russian or Spanish) to English? 

Is it a one to one map? or one to many? or many to one?

**Comment by arqex** [comment]
I guess the Spanish and the Russian problem is not the same. Spanish keyboard uses same chars than the English one, so the problem with Spanish was rather a collation than a mapping one.

**Comment by bao-qian** [comment]
@arqex 
probably I didn't express myself clearly.
let's say you want to map Spanish `á` to English `a`, how about the reset Spanish character? Could you give a list of map for reset Spanish character?

**Comment by cpkio** [comment]
I would oppose the original topic question to search in English while typing in Russian. And stripping diacrytics from characters (ÀÁÂÃÄÅÇăĄą for example) [can](https://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net) be done.

**Comment by bao-qian** [comment]
@cpkio that's implementation details, first I need a map for each language you want to use in multilingual search.

**Comment by dipique** [comment]
For a first implementation, perhaps it would be easier to simply provide a list of key-value pairs:
- `Key`:  Visible input character (e.g. `ă`, but not a control character like `Enter` or `Esc`)
- `Value': Translated value (e.g. `a`)

Pairs (e.g. `{ 'ă', 'a' }`) could be save and loaded as json files, and users could create their own `russian.json`, `spanish.json`, etc. config files. Once the community has generated these and they stabilize, they could be integrated as built-in profiles (better yet, just provide a link to a list of downloadable profiles).

An option to "strip diacrytics" would be a useful catch-all, but doing so isn't entirely trivial. I would leave this for later, or at least take a table-based approach rather than attempting to parse Unicode glyphs.

I think this approach allows you to create a solution that doesn't depend on knowledge of any particular language, depending instead on the .Net implementation of Unicode.
