### ISSUE TITLE
Consider a quick keyword/runner enhancement?

### ISSUE THREAD

**Issue by focusede** [Wox-launcher/Wox#1408]
Looking at the defective runner plugin, it seems that a keyword launcher could benefit from having a way to set up quick keyword launches like launchy, alfred, executor, etc.  Any chance at that being an enhencement?  A simple argument structure would make it very workable, run keyword %1, %2.  Thanks

**Comment by eytanweber** [comment]
If I understand you correctly, you want to be able to assign keywords so that, for example, you could type "prog" and have it make "Program Files (x86)" the top result. Is that correct?

I know that you can right click to make something the top result, but there are times when I want something to be the top result, but it's not even in the search list because of how many results there are. I'd like to be able to say, "When I type this, it brings up this result."

**Comment by bao-qian** [comment]
could you give some ui mockup, so I can understand your suggestion clearly?

**Comment by eytanweber** [comment]
Even zipped, the video file was too big, so here's the Dropbox link:

https://www.dropbox.com/s/62vi5l6btah6cig/20200515_151352.mp4?dl=0

As you can hear in the audio, what I want to do is be able to tell Wox that when I type "x", it brings up "y". Sometimes, searches have so many results that the one I want doesn't show up, which means I can't do the normal process of right clicking on it to set it as the topmost inquiry. I'd like there to be a custom input section so I can not only have a specific search include the file I want, but also so I can use shorthand or keywords. For example, I'd like to be able to tell Wox that when I type "pro", it brings up the "Program Files (x86)" folder. As of right now, it just shows tons of results I don't want.

**Comment by newduke** [comment]
Would a keyboard macro program suffice (eg hoststrings for autohotkey)? It would stuff "Program Files (x86)" when you type "prog*" (or whatever macro you create)

**Comment by eytanweber** [comment]
Would that only be within Wox, or would that be for all typing? If only in Wox, that would be great.

**Comment by newduke** [comment]
@eytanweber autohokey can set up the hotstring to be only when Wox is active if that is your preference.
