### ISSUE TITLE
About project, versioning and branching

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#147]
1. [Versioning](http://semver.org/), given a version number MAJOR.MINOR.PATCH, increment the:
   - MAJOR version when you make incompatible API changes,
   - MINOR version when you add functionality in a backwards-compatible manner, and
   - PATCH version when you make backwards-compatible bug fixes
2. Branching. For example, latest version 1.4.2
   - Master branch must contain latest version(e.g 1.4.2)(and dev branch for latest unstable?)
   - Every minor version must have branch(e.g. 1.0.0, 1.1.0 etc), 
3. Using the [milestones](https://guides.github.com/features/issues/#filtering), [example](https://github.com/angular/angular.js/issues/8569)

In last build we have incompatible changes in API and now some third party plugins don't work. It would be correct mark all old functions as deprecated and in next major release delete them.

Also I think need documentation for plugin developers.
And how about project roadmap?

What do you think about this? :smile:

**Comment by qianlifeng** [comment]
@roose  Good suggestions.  
I agree with your versioning and branching suggestions, it'a a good practice. I think we should follow that way in the following development. About the milestones, I will try to add some milestones we will follow next, but I can't promise the due date of the milestone, since Wox is my amateur project.  
I have marked all deprecated APIs, see [this](https://github.com/qianlifeng/Wox/blob/master/Wox.Plugin/PluginInitContext.cs#L27). We already have some simple plugin [development documents](https://github.com/qianlifeng/Wox/wiki/Create-Plugins), but we can do more. And I will think about the Wox roadmap later, and discuss with you guys. Thx.

**Comment by qianlifeng** [comment]
@roose I have added a brief roadmap for Wox. [Check it out ](https://github.com/qianlifeng/Wox/wiki/Wox-Roadmap)  

By the way, I think we can use tags for every minor version. And branches for features. What do you think?

**Comment by roose** [comment]
@qianlifeng roadmap, milestones :thumbsup:

Tags for every minor version and branches for features - i agree.
