### ISSUE TITLE
不支持输入法的顶屏

### ISSUE THREAD

**Issue by winter60** [Wox-launcher/Wox#1471]
我使用的是小鹤双拼输入法，当我在wox框中输入的字或词有候选时，不能顶屏，反而把我的文字删完。
当我执行一些命令的时候：如cmd
![image](https://user-images.githubusercontent.com/23653326/27211796-627fcca0-528e-11e7-9321-38f90f11f981.png)就会报错。

![image](https://user-images.githubusercontent.com/23653326/27211785-505decdc-528e-11e7-8861-a65d25944199.png)

提出的这个bug，作者有兴趣就调试调试，不想改就算了，反正也不影响我使用。

**Comment by lances101** [comment]
Please post your Wox version. If you are using an old version, download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

This issue was created long ago and there is no log file attached. 
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
