### ISSUE TITLE
WoxError

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#1508]
1. Wox version / commit number: 
Wox version: 1.3.444
2. Steps to **reproduce** the bug
Simply launching Wox
3. Windows version: 
Microsoft Windows NT 10.0.15063.0
4. Exception: in this [gist](
https://gist.githubusercontent.com/eugenesvk/dce0af7c2592b3e1a1164ff8dca23a00/raw/68fbb9ef485b074b1e46f6ab80786b7d1620631d/WoxErrorMessage.txt)
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`): in this [gist](
https://gist.githubusercontent.com/eugenesvk/dce0af7c2592b3e1a1164ff8dca23a00/raw/68fbb9ef485b074b1e46f6ab80786b7d1620631d/2017-07-06.txt)

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by eugenesvk** [comment]
@lances101 it's already attached, please check out the gist links in 5)

**Comment by lances101** [comment]
My bad, didn't notice it. Too many damn issues! :) 

It seems like you were using the "Switcheroo" plugin, but an older version. Right now Wox does not handle incompatible plugins well and "freezes" (a fix is on the way). 

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Once that is done, you can reinstall Switcheroo by querying `wpm install Switcheroo` in Wox. 

There shouldn't be any issues down the line, but if there are, please reply and reopen this issue.
