### ISSUE TITLE
Everything Plugin cannot be started

### ISSUE THREAD

**Issue by detrophy** [Wox-launcher/Wox#1533]
## English

Try search existing issues before you open new one

1. Wox version / commit number: 1.3.424
2. Steps to **reproduce** the bug: Open WOX and type something
3. Windows version: 10
4. Exception: <Wox.Plugin.Everything.Everything.IPCErrorException>
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
[2017-07-30.txt](https://github.com/Wox-launcher/Wox/files/1185461/2017-07-30.txt)

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by detrophy** [comment]
I've already uploaded the log file. Please look at the log file provided at the bottom of the comment above.

**Comment by lances101** [comment]
Sorry for the late comment, I thought I had replied.
I cannot replicate in any way the error Everything is throwing, therefore its possible that this is caused by a configuration issue. 

I will need you to provide some Everything Search Service logs too. [Here is how enable and find them](https://www.voidtools.com/forum/viewtopic.php?t=5790). The default debugging level should be enough, we should not need the verbose logs. 

1. Quit Wox, close Everything Search and check that the Everything Service is not running.
2. Enable debugging for the service and start it. 
3. Run Wox. Do a query so that it triggers the call to Everything and errors out. 

Upload the logs from Everything. (they should be at `C:\Windows\Temp\Everything Service Debug Log.txt`)

With that we should be able to get at least some info. Right now I'm blind as to what is going on.

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
