### ISSUE TITLE
Hide applicaction description

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1648]
Hi, is there any way to hide app desc? So it will only show applicaction's name.

**Comment by lances101** [comment]
Could you elaborate on what do you mean by "description"?

**Comment by lances101** [comment]
So you meant the subtitle string? 
This is currently possible with themes. 

[Take a look here, lines 21 and 28 in this gist](https://gist.github.com/lances101/932b00158d609f28f07e3f642e0ad8af#file-metro-server-no-subtitles-xaml-L21
)

You can download that file and drop it as a theme into %localappdata%/Wox

**Comment by lSindra** [comment]
@lances101 It definitely works and I love how it looks when I only set "ItemSubTitleStyle" visibility to collapse and as I select a result it shows more details.

That said, I think we should step up our Theme Builder process, maybe have an option there for those things. That would definitely help grow our community around Themes!

![woxtheming](https://user-images.githubusercontent.com/25848129/34825520-bc804dc0-f6ca-11e7-864a-211d021a60ae.JPG)

**Comment by lances101** [comment]
@lSindra what we really need is the ability to upload the themes to GetWox.com and be able to apply those themes from the settings Window. Eventually it will come, but we don't have somebody who dedicates all their time to Wox, so it will take time. 

I think adding more default themes that are more varied will help promote Wox more, and it's an easy thing to do. That said, bugs are still our top priority. 

I think I created an issue for this on the Web repo. Can't confirm now, I'm on my phone. 

Closing due to being solved. Reopen if needed.
