### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by janusxiaoguai** [Wox-launcher/Wox#1730]
## Known problems for 1.3.424:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
[2017-12-08.txt](https://github.com/Wox-launcher/Wox/files/1541090/2017-12-08.txt)

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
It seems like you are using "Wox.Plugin.Express", which is not an official Wox plugin therefore we cannot provide support for it. The plugin is not compatible with the latest version of Wox and therefore is crashing it. 

You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin.
