### ISSUE TITLE
how to make WOX refresh 'PATH' after change environment variables 'PATH'

### ISSUE THREAD

**Issue by pomodory** [Wox-launcher/Wox#1798]
If I change system environment variables  'PATH', what should I do can make WOX active without restart computer？

**Comment by lances101** [comment]
Wox launches applications and shell commands by invoking the executable with an argument, i.e. 
`> ping google.com` will run `cmd.exe` with the argument `ping google.com`
The shell should pull your updated path variables each time without problem. 

Could you provide a step by step use case?

**Comment by pomodory** [comment]
1.PATH value is %JAVA_HOME%\bin
2.I change the variable JAVA_HOME's value from "D:\JAVA\jdk1.6.0_21" to "D:\JAVA\jdk1.8.0_131"
3.execute below bat file with wox
@echo off
echo %PATH%
pause
4.PATH can't be change

**Comment by Chigogo** [comment]
I have the same problem. 

When I use `Cmder` to change the environment variables, `Wox` won't know anything and stays in original environment. 

So, When I use `Wox` to launch `Cmder`, due to its inheriting environment from Wox, Cmder has to stays in original environment.

Look forwarding to seeing  this problem solved by you nice guys!

[This problem puzzled me a lot, see. ](https://github.com/cmderdev/cmder/issues/1746#issuecomment-385666326)

**Comment by J4zzing** [comment]
I have the same problem too.
