### ISSUE TITLE
System.Io.filenotfoundException 

### ISSUE THREAD

**Issue by Izeton** [Wox-launcher/Wox#1820]
[2018-01-09.txt](https://github.com/Wox-launcher/Wox/files/1614743/2018-01-09.txt)

os version: microsoft windos NT 6.1 .7601 service pack 1 intptr
length:8*64

**Comment by lances101** [comment]
It seems like you are using "Wox.Plugin.Express", which is not an official Wox plugin therefore we cannot provide support for it. The plugin is not compatible with the latest version of Wox and therefore is crashing it. 

You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin.
