### ISSUE TITLE
Shell plugin needs an initial space to trigger / Make keywords match without spaces

### ISSUE THREAD

**Issue by harrynull** [Wox-launcher/Wox#1853]
### Are you submitting a bug report?
Yes

### Steps to reproduce
Type `>ping 127.0.0.1`, nothing happens.
Type `> ping 127.0.0.1`, the plugin starts to work.
I am not sure if it is expected or not, but in either way, it's annoying since the space is redundant (we already have ">" as the trigger).

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/7413706/35212012-b5c700c4-ff93-11e7-811f-462912a6d572.png)
*No result shows*
![image](https://user-images.githubusercontent.com/7413706/35212017-bac5be08-ff93-11e7-9aff-ef087eada995.png)
*It needs an initial space to work*

**Comment by lances101** [comment]
Wox, as do many other launchers, works on a basis of keywords. `>` is a keyword to activate the shell plugin. 

Some other plugins, like the Color plugin can be invoked without a space because the keyword for it is set to none. What it does then is check if the first character in a query is `#` and wait for a valid color. This approach can cause some issues:

![wox fff](https://user-images.githubusercontent.com/4784785/35215545-7f5a255c-ff5c-11e7-859c-ff0a6859d829.PNG)

While this is an extreme case as its rare to actually have a file named `#fff`, it serves as a good example of why the Shell plugin was initially developed by using keywords. 

All of that said, `>` is an invalid character for filenames, so it would be possible to make your use case possible without breaking results completely. 

Another option is actually adding the option of having keywords match without spaces, which is more global and makes more sense. Definitely a good suggestion, thanks.
