### ISSUE TITLE
The message sometimes is "undefined" when upload failed

### ISSUE THREAD

**Issue by harrynull** [Wox-launcher/Wox#1863]
Sometimes when upload failed, only a message that says "undefined" pops up.
In this case, the response from the server is
```
{"long_description": ["Ensure this value has at most 2000 characters (it has 2255)."]}
```

**Comment by lances101** [comment]
Thank you for using Wox and reporting an error, but it seems like you did not follow the issue template that we provide and your description of the problem you are having is not detailed enough for us to be able to help you. 

Wox is provided for free and is developed on pure enthusiasm of our contributors. 
Help us help you by filling in the information we request. 

**This issue is closed now.** 
You can either submit a new issue by following the template or copy the template into this issue and fill it in accordingly.
