### ISSUE TITLE
Add an option to the settings to change the position of the search bar.

### ISSUE THREAD

**Issue by 1danmi** [Wox-launcher/Wox#1867]
Add an option to the settings to change the position of the search bar.

**Comment by lances101** [comment]
What do you mean by "position"? You can already make Wox remember its last location

**Comment by laxu** [comment]
I can't seem to get this to work properly either. Even with the option checked in settings, Wox forgets it when it is restarted and goes to somewhere around the top portion of the screen. I can see that it overwrites the settings file instead of remembering what was set in it before. Tried reinstalling from scratch too.
