### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by kiliter** [Wox-launcher/Wox#1877]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)
[2018-02-01.txt](https://github.com/Wox-launcher/Wox/files/1685420/2018-02-01.txt)

**Comment by lances101** [comment]
Thank you for using Wox and reporting an error, but it seems like you did not follow the issue template that we provide and your description of the problem you are having is not detailed enough for us to be able to help you. 

Wox is provided for free and is developed on pure enthusiasm of our contributors. 
Help us help you by filling in the information we request. 

**This issue is closed now.** 
You can either submit a new issue by following the template or copy the template into this issue and fill it in accordingly.
