### ISSUE TITLE
The message sometimes is "undefined" when upload failed 

### ISSUE THREAD

**Issue by harrynull** [Wox-launcher/Wox#1894]
### Are you submitting a bug report?

Yes

### Steps to reproduce
1. Go to http://www.getwox.com/plugin/create
2. Fill in all the required information, with more than 2000 characters in description.
3. Click submit
4. A message saying "undefined" pops up. The response from server is:
```
{"long_description": ["Ensure this value has at most 2000 characters (it has 2255)."]}
```

### Wox Error Window text
N/A

### Detailed logs
N/A

**Comment by lances101** [comment]
Oh, so that's what you meant in your previous issue. I did not initially understand that you were talking about the website. This is why some context is so important!

GetWox.com needs a rework as to everything. The way plugins are handled, the way themes are generated, as well as a lot of other things. Sadly, nobody is willing to do a rework to it right now. Sorry for the trouble. 

The website [has it's own separate repo here](https://github.com/Wox-launcher/Website) and for organisational matters it would be better if you open issues related to the website there. 

If you don't want to create the issue there yourself, just ignore this ticket and I will just copy your issue's text there myself in a couple of days.

**Comment by harrynull** [comment]
issue created: Wox-launcher/Website#6
