### ISSUE TITLE
Some plugins are not working

### ISSUE THREAD

**Issue by demokedes** [Wox-launcher/Wox#1999]
Dear author(s),
I am very satisfied with Wox launcher. Before that, I was using Launchy and Alfred, I have to honestly admit, that Wox is by far the best launcher. 
But I have a challenge. Some plugins are not working in my case. I install it, and it is installed sucesfully, but after restart is not working, it is also not added under plugins, although, a new directory is created inside plugins directory. For example, 1 third of all plugins is not working in my case. Currecny converter is the first I remember. 
I was googling for this error and some users reported that this is happening due to missing python. I installed it, but a problem remains. Any idea how to solve this problem?
Regards

**Comment by alston19** [comment]
You can check the log file. it's under wox root directory.  It may be because wox the plugins themselves doesn't work. For instance, CC is writen in python2 so if your computer is running python it won't work. Also, the regrex patter of CC is out of date so it may cause an error. You can install Currency instead.
