### ISSUE TITLE
themes: Add ability to change bg form

### ISSUE THREAD

**Issue by ckesc** [Wox-launcher/Wox#208]
I will be nice if WOX give developers of themes ability to make round cornes and shadow =) 
Like [here:](http://www.getwox.com/themebuilder) 
![screenshot_1](https://cloud.githubusercontent.com/assets/2548610/5244879/47516de4-7965-11e4-86ec-d4793589004e.png)

And ability to style wox icon =)

**Comment by qianlifeng** [comment]
Yes, I tried to add corners and shadow before, but my approach doesn't  works perfect. I will try other ways, or if some of you guys can work it out, that will be awesome.

**Comment by mika76** [comment]
It would be great if you could also set rounding on the selected item...

**Comment by mika76** [comment]
Maybe this stackoverflow discussion helps? http://stackoverflow.com/questions/120851/how-do-i-create-a-wpf-rounded-corner-container

**Comment by lances101** [comment]
This **is** possible since Wox turned AlllowTransparency to True.
![possible](https://cloud.githubusercontent.com/assets/4784785/11767402/b4e6eed6-a1ac-11e5-8adb-7765e168eaf8.PNG)

Please [see this gist](https://gist.github.com/lances101/ed863ae9924284bd8cfa) as reference. 
Basically, you want to set a Margin for the border equal to the shadow radius (`BlurRadius`). 

Issue can be closed.

**Comment by mika76** [comment]
@lances101 nice - can the textbox and the highlighted item have rounding too? Also what version does this theme work with? It crashes when trying to use it on the chocolatey version.

**Comment by bao-qian** [comment]
@mika76 please download 1.2 beta 2 from github release. Chocolatey is not supported by us.

**Comment by lances101** [comment]
@mika76 the rounding on specific items would require a separate Border added to each item and an entry into the theme files. Currently that is not possible. This issue was about the background shadow, which is now possible. Please create a new issue for the elements you would want to be customizable, it's easier to keep track of things that way. 

My idea is to give every element that has a style a customizable key in the theme, so that we can come with really neat stuff :smiley:  Although, I can only see that happening only as milestone for 1.3.0

**Comment by mika76** [comment]
@lances101 Will do if you require it - but if you have a more generic idea, would it not be just better to wait for it?

**Comment by lances101** [comment]
@mika76 There is not that many things that need to be changed, but result items are one of them, keep track here #429

**Comment by Wind-Explorer** [comment]
Here is a link to a few prebuilt themes on another [repo](https://github.com/waterzhang0423/WoxAlfredTheme/)
