### ISSUE TITLE
On the latest release of Windows (Oct 2018) the Last Query Style settings don't work

### ISSUE THREAD

**Issue by oscholz** [Wox-launcher/Wox#2232]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by oscholz** [comment]
THank you for looking into this!

**Comment by MostHated** [comment]
Am I missing something? I see things that indicate there was an update in Oct or so, but the most recent one I see in any of the branches is July 15th?

**Comment by jhdxr** [comment]
fail to reproduce with 1.3.578. which version are you use? could you try the latest version to see if it works? thanks

**Comment by XENONChromatic** [comment]
I too ran into this. Restarting the app fixed the behavior to "expected behavior" that is to say, adopting my selection (empty last query), running latest W10 and latest version of WOX. Would be nice if Wox could either 

1. Update last query style without needing to relaunch the app
or
2. Automatically relaunch the app/process to get this functioning
or
3. Present a dialogue that the app needs to be restarted for changes to take effect

**Comment by jhdxr** [comment]
@carbon43 Wox works in the 1st mode as you describe.

my env:
Microsoft Windows [Version 10.0.17763.194]
Wox 1.3.596

**Comment by XENONChromatic** [comment]
No. It does not. Which is the entire point of this issue being open. 

I found this issue while I was in the process of opening an issue for this exact situation as well when I found this open issue. Clearly its affecting multiple users.

**Comment by jhdxr** [comment]
I'm not saying this is a false report. I'm saying the expected behavior should be mode 1. In addition, I cannot reproduce this issue under my env, which means I also don't have a solution for now. 
maybe someone could give more infomation or requirements to reproduce this issue.

**Comment by railapex** [comment]
I hit this too... and fortunately this issue comes up when you search "Last Query". Also this dupe issue #2058

I thought I had it by default selecting last query but suddenly that wasn't working anymore. Changing the settings back and forth didn't fix anything. Then I saw this issue, changed it back to select mode and restarted Wox -- instafix.

So it seems like the fix is to apply the last query style setting instantly (or at least include a "requires restart" label next to the setting). There may be another bug where it looses the last query style setting and defaults back to "preserve" but hard to even repro that at this point.
