### ISSUE TITLE
Everything failing to exclude subfolders

### ISSUE THREAD

**Issue by CookieSalesman** [Wox-launcher/Wox#2351]
Not sure if it's a bug!

I am getting lots of junk results from folders inside /ProgramData/
So I set programdata to be unhidden, excluded it using everything but somehow results from folders within ProgramData still show up.

For comparison, I excluded Windows and %appdata%, but those results do NOT show up...

Log from
1.3.524
[2019-02-02.txt](https://github.com/Wox-launcher/Wox/files/2825012/2019-02-02.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/9441933/52170656-4f47c700-2703-11e9-8e8e-d43d506fa011.png)

![image](https://user-images.githubusercontent.com/9441933/52170668-77372a80-2703-11e9-999d-0c961b82bb24.png)

**Comment by Cdddo** [comment]
It's because those results are not from the Everything integration, but from the Programs plugin. Right click on the items and you will see which plugin they belong to.

The Programs plugin really needs to be worked on to have more settings to be able to filter its results, because windows is full of lots of little system apps, and they clutter up the search results. It also gives what faulty results like in your screenshot, none of the results seem to have "asdf" in their name or path....

**Comment by CookieSalesman** [comment]
Yep. I discovered this stupid mistake a month or two ago. Thanks anyway.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
