### ISSUE TITLE
Is there any way to enable shadow?

### ISSUE THREAD

**Issue by VoQZHD** [Wox-launcher/Wox#2444]
![image](https://user-images.githubusercontent.com/45748775/56016998-cf039a80-5d1f-11e9-88e3-2a71f6d5667c.png)

**Comment by l5l** [comment]
Yes, you can add in `yourTheme.xaml` this:

>             <Setter Property="Window.Effect">
>               <Setter.Value>
>                 <DropShadowEffect Color="#000000"
>                                   ShadowDepth="15"
>                                   Opacity="0.4"
>                                   Direction="270"
>                                   BlurRadius="30"/>
>               </Setter.Value>
>            </Setter>

Please see example in [my themes](https://github.com/l5l/my-Alfred-Wox-Themes)

**Comment by VoQZHD** [comment]
Thx

пн, 22 апр. 2019 г. в 02:39, l5l <notifications@github.com>:

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by bao-qian** [comment]
close due to origin question resolved.
