### ISSUE TITLE
win+r wox窗口会变成一条竖线，操作系统版本，win10 1903

### ISSUE THREAD

**Issue by chaiguifeng007** [Wox-launcher/Wox#2461]
win+r ，会替换系统的运行，wox窗口会变成一条竖线。
按说win+r，是Windows “运行”的快捷键，为什么会变成wox，这是wox自己设置的吗？还是bug
Windows版本：1903
18362.53

**Comment by hijkzzz** [comment]
me too

**Comment by sen14251** [comment]
* 打开 wox 设置
* 切换至**插件**页，左边栏有个**命令行**
* 取消勾选**替换 win + R**

**Comment by oiryywiut** [comment]
我重启wox就行了

**Comment by whzecomjm** [comment]
这个bug 跟 win+R 好像没关系，升级到 1903 后， 有时候wox会突然变成竖线。

之后发现把 python 的 path 去掉，还有wox地址设置也清空，就没这个bug了。

**Comment by ljhui** [comment]
同遇到，时不时遇到这种搜索框变成竖线的情况，不得不重启wox，挺烦人的，系统版本也是1903

**Comment by zly19540609** [comment]
同遇到，时不时遇到这种搜索框变成竖线的情况，不得不重启wox，挺烦人的，系统版本也是1903

**Comment by HsunGong** [comment]
> * 打开 wox 设置
> * 切换至**插件**页，左边栏有个**命令行**
> * 取消勾选**替换 win + R**

建议关闭这个issue，问题已经解决。

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by chenqinA** [comment]
thanks
