### ISSUE TITLE
CPU Consumption | Battery Drain

### ISSUE THREAD

**Issue by pragun-sharma** [Wox-launcher/Wox#2565]
I have noticed that wox always always takes up 1-3% CPU usage even when it sits idle. All the indexing has been done by 'Everything' but still it eats up CPU usage. If you have a look at the battery drain apps, it consumed 6% even when i didn't use it explicitly and it was running in the background. Isn't it too much?
Version is 1.3.578
![Annotation 2019-08-07 161041](https://user-images.githubusercontent.com/21987886/62617051-a20e6f80-b92e-11e9-9080-a3d1afee6a76.png)

**Comment by Vicropht** [comment]
Have you installed any other plugins? Using too many plugins might be the reason why it's taking up more resources

**Comment by pragun-sharma** [comment]
> Have you installed any other plugins? Using too many plugins might be the reason why it's taking up more resources

Nothing. Just the default plugins it came with.

**Comment by HsunGong** [comment]
To [Vic](https://github.com/Wox-launcher/Wox/issues/2565#issuecomment-522320746)
In my opinion, plugin will start only after you trigger it using `keywords`.

To [pra](https://github.com/Wox-launcher/Wox/issues/2565#issuecomment-526565247)
I think the usage is hard to cut down, due to the core of wox. But your `CPU-freq` does matter for this usage. Maybe you have to bear this.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
