### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by Lovesakura** [Wox-launcher/Wox#2575]
希望可以改进wox的安装为便携式的或可以更改安装位置

**Comment by HsunGong** [comment]
Similar to #2587

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by bao-qian** [comment]
duplicate #629 

Please try new release https://github.com/Wox-launcher/Wox/releases
new version support portable mode.
If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
