### ISSUE TITLE
VS2015 develop help

### ISSUE THREAD

**Issue by VictoryAnn** [Wox-launcher/Wox#2632]
ERROR ：CS0006	Metadata file 'E:\Program Files\Wox-1.3.524\Output\Debug\Wox.Infrastructure.dll' could not be found	Wox.Plugin.PluginIndicator	E:\Program Files\Wox-1.3.524\Plugins\Wox.Plugin.PluginIndicator\CSC

when I build the project  ,there are  like this  CS0006	Metadata file  total  21 errors

how to solve it ?

**Comment by alekhyareddy28** [comment]
The Wox.Infrastructure project is not being built which is causing this issue. This might be happening because it has a pre-build event of using xcopy to copy the Unicode_to_hanyu_pinyin.txt file from the packages\Pinyin4DotNet*\pinyindb\ folder to the target directory and xcopy exits with an error code because the path to Wox has a space in it (Program\<space\>Files). It seems to be the issue in your case as well. I fixed this issue by ensuring that the path does not have any spaces.

**Comment by bao-qian** [comment]
check new version from master, which use vs 2019
