### ISSUE TITLE
how can I install a third-party libraries in embedded python 

### ISSUE THREAD

**Issue by kongminhao** [Wox-launcher/Wox#2715]
在您内嵌的python中，我能够安装其他的第三方库嘛？

我该怎么做呢？对windows不是很熟悉。

**Comment by ikopysov** [comment]
I'm not sure it has embedded python now, because it seems that it uses my python.
If you want to create a plugin that requires some 3thd party dependencies, my solution is to install it directly to your python env and use it in your plugin's code.
Also if you have multiple python versions you can configure it in Wox's settings: General -> Python Directory

**Comment by bao-qian** [comment]
wox did not embedded python, it use what ever python installation you installed on system.
