### ISSUE TITLE
After installing Wox, the windows search bar doesn't work.

### ISSUE THREAD

**Issue by zaferaltan** [Wox-launcher/Wox#2721]
Hi,

So after I installed Wox, the default windows 10 search bar doesn't work anymore.
I attached a screenshot with an example below.

It also won't work when uninstalled. Everything has been uninstalled including the Everything plugin.

![Annotation 2020-02-05 143354](https://user-images.githubusercontent.com/39789088/73846397-c3401200-4824-11ea-964a-a6f20a33b8a5.png)

**Comment by galvanized** [comment]
This is likely an issue with a recent Windows update. I've personally just discovered Wox after getting tired of dealing with it breaking! TechRadar reports the problems may be due to KB4532695.

To be clear, I do not have Wox installed, but I do have the issue mentioned. As such I attribute it to Windows, not Wox.

**Comment by slinkycookie** [comment]
It's a widespread Windows issue unrelated to Wox

**Comment by zaferaltan** [comment]
@galvanized @slinkycookie Thanks a lot! Probably a coincidence that it broke after I installed Wox. Will use Wox instead of it then.
