### ISSUE TITLE
do not work with windows 10

### ISSUE THREAD

**Issue by czhang03** [Wox-launcher/Wox#279]

**Comment by qianlifeng** [comment]
Didn't install windows 10, maybe I will take a look at this after Window 10 release :smile:

**Comment by alterdaemon** [comment]
For me it's working fine under Windows 10 (last three builds on fast channel)

**Comment by deltaidea** [comment]
Windows 10 Pro, build 10130, Wox works as expected.

**Comment by Shen-Shuyi** [comment]
win10 family works OK, but always error when startup with win10 open

**Comment by skotzko** [comment]
@qianlifeng any update on this? Still doesn't work on Win10 after release.

**Comment by alterdaemon** [comment]
@skotzko what's the problem exactly? I can confirm that beta version works on the current release as it has been working on technical versions too.

**Comment by skotzko** [comment]
@dgutkowsky I just reinstalled the beta on Win10 (by downloading latest Github release and moving the unzipped beta folder to Program Files x86) and once I launch Wox, it has no built in plugins at all (e.g. there is no program search, can't launch settings, etc). Maybe I installed wrong?

**Comment by alterdaemon** [comment]
@skotzko maybe it is the case, can't tell why you have problems... just be sure, it is local, not the problem of Wox itself.

**Comment by skotzko** [comment]
@dgutkowsky hmm, okay. Is that the correct install approach? There are no instructions so wasn't 100% sure. Tried the choco install earlier which didn't work, guessing it's the old version.

**Comment by alterdaemon** [comment]
@skotzko I am running it portable, no installer. Be sutre that you firewall does not block the Wox and Everything (it makes connections on localhost)

**Comment by skotzko** [comment]
@dgutkowsky Hmm. This is so weird. It's unzipped, given administrator access, and explicitly allowed through the Windows Firewall.

**Comment by alterdaemon** [comment]
@skotzko sorry to hear that,  I must say I can't imagine using Windows without Wox anymore ;)

**Comment by skotzko** [comment]
Yeah, this is frustrating. Clear install instructions would be much appreciated, as all the documentation has nothing on this.

**Comment by skotzko** [comment]
Okay, I figured it out. **Here's how to fix it when installing [the beta](https://github.com/qianlifeng/Wox/releases/tag/v1.2.0-beta)**:

### Problem 1 Fix: Getting Wox Beta to see its assemblies
1. The ZIP folder is blocked by Windows for security reasons when downloaded.
2. Right click on the ZIP folder (before extracting), click Properties. Then select "Unblock".
3. Hit "Apply".
4. Extract the folder.

![wox](https://cloud.githubusercontent.com/assets/311226/9888693/4ef7c1d2-5bab-11e5-9b80-d633b24e730e.png)

This will fix the issue of being able to run Wox--after inspecting the logs after the error, it was clear that Wox could find its plugins but could not load the plugin assemblies because they were blocked.

### Problem 2 fix: Getting Wox beta to start at system startup

Now to the second issue: having Wox actually start up with Windows. First, I unzipped it to C:\Program Files, but no matter what I did (including settings tweaks), Wox woudln't start with Windows. The fix is to make the unzipped folder live in a folder that doesn't require elevated permissions to write to. So:
1. Copy the folder to a non-System folder (i.e. a folder that does not require elevated permissions to write to). I put it in `C:\Documents`.
2. Run Wox and everything is happy.

This issue, as far as I can tell, is because Wox is designed in such a way that it writes data back to the folder where it is contained, and so this requires admin permission to do anything (including start Wox at system startup). Hence, it wouldn't start at startup even though the settings were correct.

I may have some pieces of this off, but wanted to post the fix I got to work here so others can find it.

**Comment by alterdaemon** [comment]
good for you!

**Comment by bao-qian** [comment]
Hi guys, good news.
Although you still need to put Wox under `%userprofile%`, but you shouldn't need to manually **unblock** it now.
Please try [build 1.2.787](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.787/artifacts).
If problem indeed resolved, please tell me. if not, please reopen this issue.
