### ISSUE TITLE
I can see "Empty Last Query" clearing the input....

### ISSUE THREAD

**Issue by ianyepan** [Wox-launcher/Wox#2795]
Let me start by saying a big thank you for maintaining this app!

One small issue: I've set "Empty Last Query" and it generally works fine. However, I can often see Wox clearing the previous input the next time I invoke Wox, which **results in a sudden flash of disappearing old input**. This is the behaviour I would like to avoid. 
Let me know if my explanation is unclear. Thank you in advance!

**Comment by enria** [comment]
Hi, guy, I'm a user of Wox.
I know what you are talking about, and it trouble me too. 
In addition, I have found many bugs or something make me uncomfortable in Wox, and I notice that the developers has rarely fixed bugs recently.
 So I develop an alternative. It's github url is here, [Beefalo](https://github.com/enria/Beefalo). 
If you know how to run it with Python, you can give it a shot. Sorry for it's Chinese display language, I will translate it into English in a few days (maybe 😆).

**Comment by ianyepan** [comment]
Hi @enria! I just checked out your alternative and it seems promising. I do read Chinese so that's no problem for me -- however, do you have a more detailed installation instruction? I'd love to try it over the next few days.

Cheers!

**Comment by enria** [comment]
The installation document is here, [安装](https://github.com/enria/Beefalo/blob/master/安装.md). 
I have tested it with windows sandbox, everything is fine.
Before you follow the steps of installation, you should pull the repository again.
If you have any question or want report a bug of Beefalo, you can commit a issue at it's [repository ](https://github.com/enria/Beefalo/issues) .

Have fun!

**Comment by santbohara** [comment]
@enria Thanks, my issue solved. Developer should review this.

**Comment by bao-qian** [comment]
@enria 
This project is back to active development, there are several new release recently https://github.com/Wox-launcher/Wox/releases

@ianpan870102 
could you try new release, if that not help, could you give an gif to show your problem?

**Comment by iksi4prs** [comment]
@bao-qian 

I see this behavior too on slow/medium speed computer.
when Wox window appears, the last-query is shown, and then deleted.
I think the problem is that clearing the text "ChangeQueryText(string.Empty)" is done when the window becomes visible in "OnHotkey".
I have changed that to clear the text when the window gets hidden, and this solve the problem in 99% of the cases.
The 1% that still not working is when the text is a word which has no suggestion.
Eg if you write noRepad (which will have no suggestions), then close and re-open, it will filcker for a short time.
I think it is related to the fact that in the MainWindow.xaml,  QueryTextSuggestionBox has binding both to QueryTextBox and ResultListBox, but I'm not sure and dont know how to solve this, because I have no clue in WPF.
If you want I can do a PR, so you can check and see.
Anyway, on slow/medium speed computer it is reproducible can be seen/debugged.

> @enria
> This project is back to active development, there are several new release recently https://github.com/Wox-launcher/Wox/releases
> 
> @ianpan870102
> could you try new release, if that not help, could you give an gif to show your problem?

**Comment by ianyepan** [comment]
@bao-qian @iksi4prs 
Hi guys, thanks for the replies. I just reinstalled Wox and updated to the latest version `v1.4.1129`, and sadly the described issue still persists.

I tried to record the "clearing-input flicker" as a GIF, but the frame rate is too low for the effect to show.

**Comment by Aldiyazov** [comment]
Issue persists on latest version, speed of computer not a variable since I'm running a Ryzen 5 5600X. See gif below.
![ezgif com-optimize](https://user-images.githubusercontent.com/30394370/102018101-fca9ae00-3d62-11eb-9372-386a672f4ec1.gif)

**Comment by Eve-Sama** [comment]
I can see it too. Why can not clear by itself when search is disappear?
