### ISSUE TITLE
FileNotFoundException for deleted shortcuts

### ISSUE THREAD

**Issue by sheavner** [Wox-launcher/Wox#280]
I've deleted some folders and shortcuts from my start menu, but Wox keeps looking for them.   On startup I get a huge error window saying file not found exception on StartMenu\Programs[Subfolder][Link.lnk].

![image](https://cloud.githubusercontent.com/assets/1063975/7496597/d6578f4e-f3c9-11e4-9f87-04a578fb6810.png)

v1.1.1

**Comment by drmohundro** [comment]
I just recently ran into this as well. To get around the error for now, you can clear out your image cache file (find where wox.exe is located and then go into the `Config` directory beside it and remove the `ImageCache.dat` file). Note that you'll need to stop wox.exe first. Because I installed wox with [Chocolatey](https://chocolatey.org/packages/wox), my ImageCache file was located at `C:\programdata\chocolatey\lib\wox.1.1.1\tools\Config\ImageCache.dat`.

**Comment by sheavner** [comment]
Thanks.   Removing image cache worked here.

**Comment by qianlifeng** [comment]
This issues has been fixed in V1.2.0 beta, you can try it

**Comment by drmohundro** [comment]
Thanks! Just downloaded it and using it now - so far so good!
