### ISSUE TITLE
Active Wox by shortkey, but the focus is on other application.

### ISSUE THREAD

**Issue by beviz** [Wox-launcher/Wox#3056]
## Steps to reappear:

1. Toggle on "Hide Wox When focus is lost" in Settings/General
2. Active Wox by shortkey, and type something
3. Click other application, Wox should be hidden
4. Active Wox by shortkey again, and try type something. the focus is on previous application.

## Testing Version:
1.4.196

I'm confused why such basic bug hasn't been fixed. Is it a new bug on this version or an old one from thr first release?

**Comment by Tataru-Taru** [comment]
I have the same issue.

It seems like Wox isn't actually closing the window when you click the focus off, which results in the Activate Wox hotkey not refocusing the Wox window, but instead just making it visible again.

The Wox Hotkey needs to pull focus to Wox when pressed, instead of just making search bar visible.

**Comment by lujiaxing** [comment]
Same problem.
When the Wox is actived by a shortkey, and the focus is on another application, Wox won't get focus, all inputs will run to other application
