### ISSUE TITLE
UI will freeze when do queries.

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#33]
Some times, when user input some queries, the UI will be freezed and waiting for the results returned, which is a very bad UE.

**Comment by qianlifeng** [comment]
The root cause is Result Panel try to load all results and load a lot item icons at the same time. If we didn't show icon of the results, there will be no problems.

**Comment by orzFly** [comment]
Loading lots of icons at the same time could be very horrible if the system
has high IO load. Maybe the icons extracted from Windows Shell should be
cached since there may be more IO request than one per file (Expanding
shortcuts, IconOverlays like Dropbox sync status and TortoiseGit status).

Also, loading results should be async.

BTW, if you want to add support for plugins which uses a system process, I
think it's very important to support async results.

**Comment by qianlifeng** [comment]
I think WPF UI Visualization will solve this kind of issues. It will only load user visible items on demand, I will check the performance after implement UI Visualization. If it still freeze the UI, we can try to cache icon from window shell or image file. Currently, Loading resulsts from plugins are already async in different thread. What's the different between Sync request in new thread and Async request?

**Comment by qianlifeng** [comment]
After using UI Virtualization and Image Cache. It works ok now. 200181623ec75aa9d4913f1d6bd072db9071a584 & fe7afe3dec943c1de1181c7a74dde4f6d6e63233
