### ISSUE TITLE
Allow Windows 10 automatic accent color

### ISSUE THREAD

**Issue by mika76** [Wox-launcher/Wox#330]
Windows 10 has the option to Automatically pick accent color for it's windows which makes they adapt to your wallpaper. How about getting wox to follow this option too?

Seems it might be automatic if no colors are chosen? (http://stackoverflow.com/questions/31831917/change-accent-color-in-windows-10-uwp)

**Comment by lances101** [comment]
The link you provided is for UWP (Universal Windows Platform, aka, "Metro Apps"). 

Still, this could be possible. The main problem is that the accent colors are barely documented anywhere. 

This is where I am right now. I am changing the system accent color, so the taskbar changes as well as the application itself. Trying to figure out why the color is lighter (bear with the shitty quality). 
![Accents Example](http://i.imgur.com/N91GHjr.gif)

**Comment by lances101** [comment]
**Update**, this is an example theme that uses blur. 
![Blurred Themes](http://i.imgur.com/jBGfSyY.png)
![Blurred Themes](http://i.imgur.com/EzXZOOh.png)

Accent colors still need more poking. I only get the soft color. [Found this](https://github.com/VladimirAmiorkov/Windows-8-8.1-start-screen-colors-into-desktop-application), but I really don't want to be constantly doing WinAPI calls to see if the color itself changed... Then again, maybe I'll have to.

**Comment by qianlifeng** [comment]
Blur is awesome :smile:, how do you make it blur? We tried Win32 API before, but has performance issue

**Comment by mika76** [comment]
Man, it looks great! (Personally I love the dark one with the light border)

I don't think that it's such a necessary thing for it to catch live events of color changes. It would not be bad to just change on showing the wox search form. Also WinApi is crappy but it's a windows app so why not?

**Comment by lances101** [comment]
@qianlifeng, same here! Everything I had tried a performance hit... I knew that [Classic Shell](http://www.classicshell.net/) did it in some way, but they have not been releasing source code for **2 years** ! :astonished: 

So I hit their forums and found [this](http://www.classicshell.net/forum/viewtopic.php?f=7&t=2050&view=next) and got to know about `SetWindowCompositionAttribute`, which is documented ... fucking NOWHERE! MSFT has no documentation on it. At all. So eventually I came to [this](https://github.com/riverar/sample-win10-aeroglass). 
_//end of rant_

Anyhow, blur/accent can be changed on the fly, while swapping themes. So I've decided implementing it as part of the theme files, because you would really want it on a theme-by-theme basis. 
At the current state by adding 

```
 <!-- Accent Mode: 0 - none, 1 - Accent color, 2 - Accent with transparency, 3 - Blur -->
<system:Int32 x:Key="WindowsAccentMode">3</system:Int32>
```

into any theme file the accent mode gets set upon load. Still can't think of a more elegant way of setting it, though. Any ideas on this?

@mika76, WinApi is not that bad when it's documented! :sweat_smile: 

**Edit**:
Forget about the AccentMode integer. I will convert it to a boolean for Blur, because the rest of the options seems to give me unpredictable results :neutral_face:  
I will figure something out with the accent colors separately (I want them to display correctly in the theme preview).  **Small edit**: Turns out there's 473 accent colours. Crap.

**Comment by qianlifeng** [comment]
Awesome, I like the SimpleBlur-Black theme. By the way, can user change the blur value? for me, I would like it to be more blur
![image](https://cloud.githubusercontent.com/assets/1725475/11063432/9169e28a-87f1-11e5-8410-2f6bc64fdf81.png)

**Comment by qianlifeng** [comment]
By the way, you missed the blur setting in the theme setting window

**Comment by lances101** [comment]
@qianlifeng The blur setting is NOT in the settings window. The blur setting is in the Theme file.
`<system:Boolean x:Key="ThemeBlurEnabled">True</system:Boolean>`
Setting this to false will turn the blur on that theme off. 

_Regarding the blur intensity_, I have yet to find a way to change the blur amount. Again, nothing regarding bluring/accents/etc is documented. 

**Edit**: Okay. I think I am finally happy. Transparent background with an image as the border  :smile: 
![Border with image](https://cloud.githubusercontent.com/assets/4784785/11069570/000e5952-87d7-11e5-9f3e-41d7a6dab22c.png)

**Comment by bao-qian** [comment]
How could I get rid of the border?

**Comment by lances101** [comment]
@happlebao Set the brush thickness of WindowBorderStyle to 0

```
<Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="BorderThickness" Value="0" />
    </Style>
```

**Comment by bao-qian** [comment]
@lances101 do you know why preview of simpleblur-black and simpleblur-white in theme setting is transparent? I'd like to add blur setting to it.
![transparent](http://i.imgur.com/C8Sqni0.png)

**Comment by bao-qian** [comment]
Wow, I found the more blur settings. Just add alpha channel to background. There may be some duplication in xaml since I'm not familiar with WPF.
![black](http://i.imgur.com/gVZHqoE.png)
![white](http://i.imgur.com/A7BNaal.png)
@qianlifeng @lances101

**Comment by bao-qian** [comment]
Anybody could test whether this blur things working with Windows 7/8 ?

**Comment by lances101** [comment]
> do you know why preview of simpleblur-black and simpleblur-white in theme setting is transparent? I'd like to add blur setting to it.

The whole blur-setting thing is done via WinAPI and changes a property of the `Window` object. I cannot think of a way of making it use the same feature that `MainWindow` uses. Instead, we could fake the blur in the preview somehow. That should work just fine. 

> Wow, I found the more blur settings. Just add alpha channel to background. There may be some duplication in xaml since I'm not familiar with WPF.

Yes, XAML is pretty much flexible in what you can change just via resource dictionaries. And I think at the current state Wox's Themes are in a pretty good state. For example, [as I've showed here](https://cloud.githubusercontent.com/assets/4784785/11069570/000e5952-87d7-11e5-9f3e-41d7a6dab22c.png) you can set a background image to the WindowBorderStyle and it will work just fine :) 

And yes, if you set it to white and change the opacity it will will more "cloudy" :smiley: The problem is finding a way to change the **force** of the blur. [See a little example here](http://imgur.com/a/AC6jR)

> Anybody could test whether this blur things working with Windows 7/8 ?

From what I've read, this should work just fine on Windows 8 (**not tested**). Doubt that it will work on Windows 7

**Comment by bao-qian** [comment]
> we could fake the blur in the preview somehow. That should work just fine. 

Yeah, I agree with you. But how could you make it transparent in theme preview?

> The problem is finding a way to change the **force**

Sadly, the **force** seems unchangeable.

**Comment by lances101** [comment]
I thought of using the [XAML's Blur Effect](https://msdn.microsoft.com/library/ms742795%28v=vs.90%29.aspx). The only problem is that it blurs the actual image, not everything behind it. 

So, if we want it to be identically correct to the real representation, we would need to crop the wallpaper to the preview's size, apply it as background to the preview and then blur it.

**Comment by A7ocin** [comment]
@happlebao how did you manage to make blur work on windows 10?

**Comment by lances101** [comment]
@A7ocin are you asking about the implementation of the blur or actually using blurred themes in Wox? 

As for Wox, just choose a blurred theme and restart Wox. 

As for the implementation, we are using an undocumented function, `SetWindowCompositionAttribute` to be specific. Read my posts in this issue for more info and / or take a look at [this blog post](http://withinrafael.com/adding-the-aero-glass-blur-to-your-windows-10-apps/)

**Comment by RikKoedoot** [comment]
sorry, how do I add blur @bao-qian
