### ISSUE TITLE
[Web Searchs] default to google search

### ISSUE THREAD

**Issue by PierBover** [Wox-launcher/Wox#333]
In Alfred google is the default search without having to use any command. Is it possible to have something similar in Wox?

What I mean is searching in google without having to type "g ".

**Comment by deltaidea** [comment]
Yes, you can leave the keyword empty for any plugin to have it activated immediately when you start typing.

**Comment by lances101** [comment]
@deltaidea, I don't think that would work. While the web searches plugin would be queried, it requires a keyword to be set so that a result leading to Google would pop up. 

What @PierBover could do as a temporal fix, is add a hotkey for the search plugin.

**Comment by qianlifeng** [comment]
@lances101 is correct, we can't do this now.

**Comment by PierBover** [comment]
> What @PierBover could do as a temporal fix, is add a hotkey for the search plugin.

Thanks I will do that in the meantime.

It's a shame, Alfred is the one thing that keeps me from fully moving to Windows.

**Comment by bao-qian** [comment]
This is not possible as the web search is implemented as a plugin, not a built-in functionality.

**Comment by lances101** [comment]
@happlebao I don't think we actually need the web-plugin to be part of built-in functionality for this to work. A simple fallback functionality could added to Wox that would run a specific plugin for when there are no results. The plugins would implement a "IFallback" interface and give fallback results for when there are no other results for a query. 

I tried a fast and dirty implementation when this issue was just created. The problem I found was that there is no way of tracking dispatched querries as of now, so I couldn't know when I should actually call the Fallback routine, because some plugins kept on popping up their results through API.PushResults.

**Comment by bao-qian** [comment]
@lances101 This is the multi threading design, every plugin will utilize `API.PushResults`.
It will mess up all the things if you want to create a event when all plugins in all thread is executed, because there is a [ongoing refactoring](https://github.com/qianlifeng/Wox/pull/347).

**Comment by lances101** [comment]
@happlebao, yep, I am aware of your ongoing refactoring, so I am not working on any changes until things settle down a little.

**Comment by bao-qian** [comment]
Implementation I suggest is using `IFallback` and `Task`.
Instead use `ThreadPool.QueueUserWorkItem` to deliver query, we should use `Task.Start`, and combine with `Task.WhenAll` and `ContinueWith`.
Since this is a lot easier when using `Task` and `Task` meant .NET 4.
So we will implement this when .NET version upgraded.

**Comment by bentsai** [comment]
I suggest making this configurable since not everyone's default search engine is Google. For example, duckduckgo.com :) This is how I have Alfred configured.

**Comment by tzakrajs** [comment]
Maybe you could add a global setting that pre-populates all new Wox queries with any text you want (e.g. "g").

**Comment by bao-qian** [comment]
as discussed above, this won't be implemented.
