### ISSUE TITLE
Send key strokes to an open window/application from a plugin

### ISSUE THREAD

**Issue by antitoxic** [Wox-launcher/Wox#337]
I want to make a plugin for Wox that can send keystrokes to another application window. A window of a application different than Wox.

I need this so I can make Wox automate keyboard shortcuts by fuzzy typing commands of applications menus.

Example uses:  run "Flatten layers" or "Show Layer Blending Options" in Photoshop by fuzzy typing "ftten" or "layer" in Wox. If I know the previously active application window this also removes the need of namespacing.

The result will be something like Sublime text editor `Ctr+Shit+P` but for every app.

Can you make Wox send key strokes to other windows and pass the name of the previously active window in plugins query method?

**Comment by lances101** [comment]
@antitoxic Wox is _not_ a macroing tool and I doubt that @qianlifeng will add functionality for input emulation, but passing the information of the topmost window could be interesting for application specific queries.

Although, you can include the topmost window-tracking functionality into your macro plugin by yourself.

**Comment by antitoxic** [comment]
@lances101, yes topmost winfow / last active window fits Wox purpose perfectly, it gives extra context.

Additionally I think that the appeal of Wox is also about abstracting complexity of writing shortcut scripts as far as I see from the plugins listed.

Otherwise, can recommend a way to build macro plugin in combination with Wox?

**Comment by lances101** [comment]
In regards to recommendations of how to build it... _IMO_, at first, you should define how complex it will be, because this will define a lot of things. 

Any way, you would need a way to create the scenarios inside of Wox's settings tab. Take a look at Razer Synapse, it does it in a simple manner:
![](http://i.imgur.com/RY7Kqze.jpg)

Then, you would need to have a module in your plugin that would execute those scenarios. 
If you have any specific questions - feel free to ask them. Although, I'm not sure this is the place to discuss them.

**Comment by bao-qian** [comment]
It is possible.
You could write a plugin using http://www.autohotkey.com/.
