### ISSUE TITLE
.NET version collector

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#354]
Upgrading to a newer version of .NET has been requested by many contributors.
See https://github.com/Wox-launcher/Wox/issues/325 and https://github.com/Wox-launcher/Wox/issues/236, and of course I prefer .NET 4.5 myself.

I'd like to write a .NET version collector before we decide which version of .NET we should use.

**Comment by bao-qian** [comment]
If we upgrade the .NET version, when install plugin written in .NET 3.5, will it caused conflicts?

**Comment by lances101** [comment]
@happlebao  usually the upgrade from lower to higher .NET versions is smooth. Even if it does cause some problems, I think that it is still worth it.

**Comment by lances101** [comment]
@happlebao, by the way, what do you mean by "Version collector?

**Comment by bao-qian** [comment]
@lances101  Once you launch Wox, Wox should send your UUID of your machine and OS/.NET version info to some server.

**Comment by koobs** [comment]
@happlebao Please ensure this is an opt-in by default mechanism, with an explanation as to what the value is for you, to encourage users to allow it. Clarification up front on whether this is a once-off information collection, when it happens (post-install? initial-startup?) or whether it is regular and at what frequency (interval) would also be worthwhile.

Personally I believe the decision as to what .NET version you ultimately choose should be based on it's value to the progress, feature-set and productivity of development and project in general, rather than what any particular subset of the (only CURRENT) userbase has installed

**Comment by bao-qian** [comment]
@koobs Thanks for your advise, it is insightful. 
My currently thought is collect at every startup, if it changes, then send it.

**Comment by koobs** [comment]
@happlebao If the plan it to consistently gather information, don't forget to include an option

1) During installation
- [ ] Enable anonymous data collection (Windows & .NET Version) (Opt-in highly preferable)

2) In Settings

Also, don't forget to include privacy information that details what information is collected and what it's used for. This can be in the form of a link to the website (privacy.html) or similar in the program (during install and in settings)

**Comment by bao-qian** [comment]
It won't gather any info after wox has been upgraded to .net 4.5. This will be just a temp work.

**Comment by luisrudge** [comment]
I don't see this as really necessary.. Batch the upgrade to .net 4.5 with a bunch of nice features and release version 2.0 (breaking change). Done. If someone can't upgrade .net version, just stick with the 1.2 version.

**Comment by bao-qian** [comment]
Since this is anti privacy and unnecessary, I won't consider this anymore. Instead, I will include .NET 4.5 with installer.

**Comment by koobs** [comment]
Thanks! You can use the time you would have spent on this on improving the UX / search algorithm of Wox instead ;)

**Comment by bao-qian** [comment]
Again, thanks for suggestions.
