### ISSUE TITLE
Request: Drag and drop

### ISSUE THREAD

**Issue by Ack0** [Wox-launcher/Wox#398]
Can you add drag and drop support? Example: I drag some .lnk (or .exe, wathever), press alt+space and then drop inside the window.

**Comment by bao-qian** [comment]
drag some .lnk and then in order to do what?

**Comment by Ack0** [comment]
To create keywords like Executor. Look: http://i1-win.softpedia-static.com/screenshots/Executor_3.png

**Comment by bao-qian** [comment]
What you should do is add one more index folder in Program plugin.
![see](http://i.imgur.com/G23Yk4D.png)

**Comment by Tagirijus** [comment]
Sorry for opening up something that is already closed, but: did something change so that drag and drop is available now when creating an own plugin? If so, I would think about writing a plugin so that I could use Wox to search for files of my music programs and synths and so and then I could drag them into the music software from Wox. Is this possible in Wox (technically)?
