### ISSUE TITLE
Wox window is not centered

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#411]
![screenclip](https://cloud.githubusercontent.com/assets/7104786/11482121/31f22876-9773-11e5-950a-bd65f9232e26.png)

Build 1.2.603, Windows 10x64, 14 inch laptop, x900 res
Not sure if this is the desired functionality.
Please advice if is not the correct feedback format/channel.

**Comment by bao-qian** [comment]
The position is a known bug. Please provide your dpi and screen resolution. (900 multiply what?)

**Comment by rickmed** [comment]
sorry, 1600x900, 14 inch = 131 PPI

**Comment by lances101** [comment]
I am not 100% sure, but I am coming to a conclusion that this happens because we read the value from the `Screen` class, which contains actual pixels, while _WPF_'s `WindowLeft` stores the value in "device independent pixels" (**DIP**). So for us, with a "normal" DPI it saves and displays just fine, but people with higher density screens are experiencing problems. 

The fix would be to _store everything in DIP_. And only convert `Screen` pixels to DIP when trying to find the screen center

**Comment by bao-qian** [comment]
Ideally, I'd like to get rid of all of WinForm api usage....

**Comment by lances101** [comment]
@happlebao I don't think that is completely possible :disappointed: 

@ricmed205, please [try this build](https://github.com/lances101/Wox/releases/download/bugfix-411/bugfix-411-build-1.zip). I've added some `TransformToDevice` conversions for pixels, which should convert them to actual **DIP** that WPF uses. I cannot test it on a higher DPI screen, but I did try setting up the scaling in Windows up to 125% and it seemed to find the position just fine every time. 

Please tell me how it went.

**Comment by jcpeterson** [comment]
I already reported this in #317

**Comment by lances101** [comment]
@jcpeterson could you try [the build I linked](https://github.com/lances101/Wox/releases/download/bugfix-411/bugfix-411-build-1.zip) in a post above yours? If the DIP fix works, I'll make an actual fix and PR

**Comment by DarrenCodes** [comment]
Could everyone experiencing this problem try this [build](https://github.com/DarrenCodes/Wox/releases/download/bugfix/Relative.Positioning.Fix.zip).

I would appreciate the feedback.

**Comment by bao-qian** [comment]
Please use #271 to discuss position problems in the future.
