### ISSUE TITLE
Search Bar flickering

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#435]
As reported 
#428

> @PengKISS:"打开的时候有时会闪一下 http://pan.baidu.com/s/1mht9yOw
> 
> @PengKISS:"It will flicker once during first launch [flickering.zip](https://github.com/Wox-launcher/Wox/files/64030/flickering.zip)" 
#271

> @highpowerxh:"I noticed that the bar will flicker, like show>disappear>then show persistently."

**Comment by highpowerxh** [comment]
As requested:
<32Bit>
2.0.50727.8670
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1038.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8670
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1038.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.1  (CLR:4.0)

< Installed Updates >
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217

< Installed Languages 3.0>
English - United States
< Installed Languages 3.5.x>
English - United States
< Installed Languages 4.x>
English - United States

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.10586 N/A Build 10586

Wox Version:              1.2.612

**Comment by happlebao** [comment]
@highpowerxh @PengKISS try [build 1.2.635](https://ci.appveyor.com/api/buildjobs/7iiek6fty7bvr9kv/artifacts/Output/release-binary.zip)

**Comment by bao-qian** [comment]
@lances101 could you reproduce this issue? I can't reproduce it. Here is what I have done:

vm hardware: 2 core + 2gb memory + hdd
1. grab a copy of [win10 vm](https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/)
2. download [.net 3.5 client](https://www.microsoft.com/en-us/download/details.aspx?id=5007)
3. tested both 1.2 beta.2 and 1.2.612

**Comment by highpowerxh** [comment]
Tested 1.2.635, still have the issue.

**Comment by bao-qian** [comment]
@highpowerxh after the flickering, did you notice that the notification area has a list of Wox icon?

**Comment by highpowerxh** [comment]
Nope, there is always only one.

**Comment by lances101** [comment]
@happlebao 
On my own machine (version collector dump below) it does happen sometimes. Note, that this is a gif of a **slowed down** video, because on my system it is really a split second. 
![flickering](https://cloud.githubusercontent.com/assets/4784785/11859805/dbbbad7a-a46e-11e5-8fed-db349e17a6b2.gif)

I think I know why this may happen, but I need time to test it. Most likely, it's because of the repositioning upon opening the Window. I'll update once I have more info

``` <32Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1040.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1040.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.1  (CLR:4.0)

< Installed Updates >
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217

< Installed Languages 3.0>
English - United States
Russian
< Installed Languages 3.5.x>
English - United States
Russian
< Installed Languages 4.x>
English - United States
Russian

```

**Update** : I was wrong. Nothing to do with positioning.

**Comment by lances101** [comment]
This is very hard to debug, since the flicker happens occasionally, and I cannot seem to figure out _what_ causes it. Sometime it is there, sometimes it is not. 

As a general rule, this should only happen if there is some code running the UI thread, that blocks it and the flicker that we see happens. Can't find what exactly causes that though. The `MainWindow` class is a little bit too heavy than I think it should be.

**UPDATE** No flickering for me in .net 4.5 branch:exclamation:

**Comment by pengzhxyz** [comment]
I think also flickering maybe caused by the .net 3.5.
There was no flickering in 1.2beta based .net4.5 before.

**Comment by bao-qian** [comment]
Hi guys, .net 4.5 is done. try [build 1.2.662](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.662/artifacts) .
Remember install .net 4.5.2+ before launch it :) .
@lances101 @highpowerxh @PengKISS

**Comment by bao-qian** [comment]
@lances101 do you have this issue now ?

**Comment by lances101** [comment]
@happlebao, can confirm, build 1.2.662 does not flicker on any of my machines

**Comment by bao-qian** [comment]
Reopen it if anybody find this issue again.
