### ISSUE TITLE
Highlighting/formatting of entries

### ISSUE THREAD

**Issue by oxysoft** [Wox-launcher/Wox#441]
Here is a mockup of how it could look like

![](http://i.imgur.com/ifsL8Rn.png)

Text could be highlighted with a variety of colors for both the main Title and the Subtitle. This would be very useful in displaying certain information for a plugin I will be making. Maybe give a fixed palette of color for consistency (which could be customized per theme obviously)

Maybe add bold and italic while we're at it too!

**Comment by bao-qian** [comment]
the plan is to support #116

**Comment by oxysoft** [comment]
will plugin developers be free to use this api to freely style the formatting of the text in their entries though?

**Comment by lances101** [comment]
As I see it, to be able to format Titles and Subtitles however plugin developers may desire, we would need to be able to pass XAML data for UI controls from the plugins  **or** parse tags inside of the Title and Subtitle strings that are returned. I vote for the latter. 

Tags like `<Bold></Bold>` are not parsed when set as a string to a TextBlock, the only way I know of dealing with this is the one [described here](http://stackoverflow.com/questions/5565885/how-to-bind-a-textblock-to-a-resource-containing-formatted-text) which involves writing a special helper that parses the needed tags. It makes it pretty flexible in terms of what is possible, although, we may require more tags eventually.

@oxysoft now, regarding the highlighting itself, we would need to create tags that parse highlighting too (i.e. `<Background="#FFF>"` or similar). Adding `TitleStyle` to `Result` so that it is then parsed by `ResultPanel` will not work, because it would apply the style to the **whole** `TextBlock`, without any possibility to select what is actually needed. 

@happlebao, what are your ideas on the implementation of this and #116 ?

**Comment by bao-qian** [comment]
@oxysoft sorry, no.
@lances101 as I said, the plan is to support #116, not this one. Tags is not needed.
1. match each result with `FuzzyMatcher`, calculate score, calculate index of bold characters.
2. store indexes of bold characters in an array.
3. bold part of `TextBlock` for given indexes. [see here](http://stackoverflow.com/questions/1797958/wpf-textblock-format-text-programmatically#1798020)

The problem would be how to calculate index, since Wox support both Chinese pinyin and Chinese Hanzi.

**Comment by lances101** [comment]
@happlebao Ah, ok. Then keep it that way and handle the formatting inside of the `FuzzyMatcher`.

I don't know the specifics with Chinese... But with English the way you described would work without any problem. 

@oxysoft Regarding the functionality you want, while formatting will not be implemented, there may be some custom control support planned for `1.3.0`. Just not now.

**Comment by bao-qian** [comment]
hi @oxysoft 
this feature has been implemented in #2817
check new release
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735
