### ISSUE TITLE
Open file or executable as administrator

### ISSUE THREAD

**Issue by PierBover** [Wox-launcher/Wox#488]
Is there a way to do that from Wox?

If not it would be awesome.

**Comment by LingForCC** [comment]
Right click or use shortcut 'Ctrl+O' on your search result will open the context menu for that specific result. For executables, there is an option for 'Run as Administrator'. 

![image](https://cloud.githubusercontent.com/assets/5373202/13025567/3b7b4b72-d245-11e5-9cdc-006cf79c89f5.png)

**Comment by PierBover** [comment]
I don't see that option but I'm on latest beta 2.

Is this some plugin?

**Comment by LingForCC** [comment]
That is possible. Since the context menu for search result is provided by a specific plugin as well, it is possible that the plugin which generates the search result doesn't support such operation. I myself disable the plugin named 'Everything'. So most of the search results are generated by 'Program' plugin which may support such operation. You could try to disable 'Everything' plugin to check whether it works.

**Comment by PierBover** [comment]
Thanks for some reason Program doesn't return anything.
