### ISSUE TITLE
Expose System Plugin Interface

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#55]
下午提交了一个calc的插件pycalc，感觉目前的插件机制实现计算器类的插件不是很方便。

目前的机制，只有在输入ActionKeyword后才能触发插件，在实现计算器类的插件时，感觉这种方式不是很方便。在launchy中，计算器插件直接输入表达式后就可以有结果，不需要任何键触发，效率比较高。

能否优化一下？

**Comment by orzFly** [comment]
不知您知道没有，计算器事实上已经自带了 #40 。

不过，这个对插件机制的修改值得进一步讨论。

**Comment by qianlifeng** [comment]
If we expose system plugin interface, will this slow down the query? Because every query will be handled by those plugins that registered as system plugin.  
Also I think this may produce mess  results, since there maybe a lot results for the same query. And the score for the system plugin needs to be considered. I think most of the system plugin created by users will try to give a large score for the result, so it can be displayed at the top of the result list.

**Comment by qianlifeng** [comment]
we will not expose system plugin interface now. Take bookmark plugin as example, we even remove it out of the system plugin since there are many unrelated results in your search (since we support fuzzy search).
