### ISSUE TITLE
Wox crashed when searching sumatraPDF

### ISSUE THREAD

**Issue by warcy** [Wox-launcher/Wox#556]
1. download from Appveyor, **build number** 1.2.805, maybe already the lastest version in master branch
2. **reproduce**: searching _sumatraPDF_ with _suma_. Wox only crashed while typing _a_, but _sum_ is alright.
3. Windows 7 x64 and Windows 10 x64
4. logs: [2016-04-12.log.txt](https://github.com/Wox-launcher/Wox/files/214225/2016-04-12.log.txt)
5. screenshot: 
   ![wox-crash](https://cloud.githubusercontent.com/assets/1590850/14447568/b56e443a-0093-11e6-9b32-5d947c8a50e0.png)

**Comment by lances101** [comment]
This happens because the calculator library that Wox uses (`YAMP`) is trying to parse and evaluate the string. As a temporal fix you can either disable the calculator plugin or set a special keyword for it. 

I cannot reproduce the error on my machine right now, therefore I don't know what exactly is going wrong since `suma` is not a valid keyword for YAMP and Wox actually filters out the queries for the Calculator plugin by the keyword `sum`.  I'll keep on trying to recreate the issue.

**Comment by warcy** [comment]
Hey lances, thanks for your reply. It works to disable the Calculator plugin.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
