### ISSUE TITLE
Wox chrashes if no proxy setting and no internet connection is available

### ISSUE THREAD

**Issue by haltug** [Wox-launcher/Wox#611]
It's not possible to run Wox without Internet connection. It chrashes immediately. Can we disable the Internet requirement?

**Comment by bao-qian** [comment]
Show me the log.

**Comment by friscoMad** [comment]
Even with proxy configured and tested is crashing constantly since 10 min ago (installed this morning worked without issues until now).
System.Net.WebException
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by bao-qian** [comment]
The whole logs file for today please

**Comment by friscoMad** [comment]
Log for reference: [2016-05-10.txt](https://github.com/Wox-launcher/Wox/files/257453/2016-05-10.txt)
The first exceptions were thrown when I was trying to run Wox twice. 
Lauchy was being uninstalled and running Wox for the first time was unable to register the shortcut, so I tought it did not start and started it again several times (until I found the icon in the icon tray).

**Comment by bao-qian** [comment]
So, you are not using setup.exe to run it?

**Comment by bao-qian** [comment]
To run it -> to install it

**Comment by friscoMad** [comment]
Yup, understand that today is my first day with Wox, I installed Wox with the installer, and I think it did run directly after install, at the same time I was unninstalling Launchy so Ctrl+Spc was still registered, and Wox did show an error about registering it. I thought it was still the installer, but soon after the Wox box appeared, I tweaked some options and hide it. As using Ctrl+Spc didn't work, I thought that somewhat it did close.
That's why started the program again from the Windows menu several times and what caused the first round of exceptions.

**Comment by bao-qian** [comment]
that's the correct steps, don't worry
wox use alt + space by default instead of  ctrl + space.
the registering is done on every startup, so just restart wox should be fine.
it seems github is not accessible (socket, not http) during startup (updater can't use proxy at this version)

temp fix: use 1.2.900 which don't have updater, and upgrade to 1.3.x when it is available .

**Comment by haltug** [comment]
Which log file? 
The error appears when I start the launcher or when I open Wox from the task bar.

---

The remote server returned an error: (407) Proxy Authentication Required.

---

Exception Type: System.Net.WebException

Source: System

Stack Trace:  
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by bao-qian** [comment]
%APPDATA%\wox\logs

**Comment by bao-qian** [comment]
>  start the launcher

what's this?

> The remote server returned an error: (407) Proxy Authentication Required.

you said you don't have internet connect right? then why there is a remote server returned error...?

**Comment by bao-qian** [comment]
@haltug @frisco82 
Thanks for report bug
please try `Releases\Setup.exe` from latest build https://ci.appveyor.com/project/happlebao/wox/build/1.3.16/artifacts

**Comment by haltug** [comment]
I have an Internet connection that uses a proxy for the communication. I got again the error without proxy settings, but it also does not work with the latest build.

The log content from the release:
[http://pastebin.com/wZtAJXTb](http://pastebin.com/wZtAJXTb)

The log content from the latest build:
[http://pastebin.com/g2BSmDkp](http://pastebin.com/g2BSmDkp)

**Comment by bao-qian** [comment]
@haltug both links are not accessible / removed...

**Comment by haltug** [comment]
@happlebao sorry, links work now

**Comment by friscoMad** [comment]
It crashes when I start the app
[2016-05-11.txt](https://github.com/Wox-launcher/Wox/files/259111/2016-05-11.txt)

**Comment by bao-qian** [comment]
thanks, new version will come out after I get off from work

**Comment by bao-qian** [comment]
@haltug @frisco82 
Thanks for report bug
please try `Releases\Setup.exe` from latest build https://ci.appveyor.com/project/happlebao/wox/build/1.3.18/artifacts
and then upload the whole log file from `%APPDATA%\Wox\Logs`

**Comment by friscoMad** [comment]
I don't get any error with 1.3.18 from this issue but no results appear and I get #614.
I tried checking for updates but no message appeared, not sure if that's the inteded response in case there are no updates.
I will leave it running to check if it manifest later as it happened 2 days ago.

**Comment by bao-qian** [comment]
@frisco82 

> I tried checking for updates but no message appeared, not sure if that's the inteded response in case there are no updates.

that's intend behavior, and your version is newer than the release in github.

**Comment by haltug** [comment]
I have an issue when I start Wox. See log please:
[http://pastebin.com/R7UVdtSp](http://pastebin.com/R7UVdtSp)

Besides that, I get no search results when I type anything in the search field.

**Comment by bao-qian** [comment]
@haltug could you try restart your computer? it seems there is another instance (wox) running.

**Comment by bao-qian** [comment]
or try to delete  `%APPDATA%\Wox\Settings\Plugins\Wox.Plugin.WebSearch\Images` directory?

**Comment by bao-qian** [comment]
The restart won't solve the problem. Delete the directory will let wox works. But the exception is another bug tracking in #614
