### ISSUE TITLE
use other explorer other than explorer.exe

### ISSUE THREAD

**Issue by smthvitas** [Wox-launcher/Wox#623]
之前用的everything是与TC集成的，搜索到的目录会在TC中打开，而不是系统自带的资源管理器。
为实现这个目的需要修改everything.ini，在其中加入类似
open_folder_command=$exec("%TOTALCMD%\Totalcmd.exe" /o /t /l "%1")
这样的配置。
查看了一下Wox\Plugins\Wox.Plugin.Everything\PortableEverything\x64\Everything.ini
其中没有这一项，手工添加也不起作用。
wox的everything能否与tc集成？

谢谢！

**Comment by bao-qian** [comment]
> Hi,
> Is there any way to specify a filer to open the file location (Open containing folder)? Wox always uses exploer.exe even the system default filer has been changed (HKEY_CLASSES_ROOT\Folder). I'd really appreciate if Wox uses the default filer when it's changed, or user can specify the filer Wox uses. Of course, Wox uses the default filer to open a folder when a query specifies a folder. This is only the case for 'open containing folder' functionality.

@terepanda

**Comment by bao-qian** [comment]
can't use chinese in company.

currently, no.

wox use `UseShellExecute` to open files, 
so if you can use <kbd>ctrl</kbd><kbd>r</kbd> to let file open in tc,
then you can use tc to open files in wox

**Comment by smthvitas** [comment]
ok,thanks~

**Comment by bao-qian** [comment]
@terepanda if you changed the default filter, could you open the directory using changed filter by using run command?
![image](https://cloud.githubusercontent.com/assets/1169912/15458375/09a24eda-2091-11e6-920d-e64605ec72b4.png)

**Comment by smthvitas** [comment]
没看懂
刚反应过来，你说的<kbd>ctrl</kbd><kbd>r</kbd>应该是<kbd>WIN</kbd> + <kbd>r</kbd>吧？
如果是这样的话，之前贴的那个命令行就可以：
"%TOTALCMD%\Totalcmd.exe" /o /t /l "%1"
这个直接在win+R中间输入，就可以打开TC并定位到%1这个文件。

**Comment by terepanda** [comment]
@happlebao 
Thank you for your reply:smile:, and sorry for missing it:cold_sweat:!  I'm afraid I might not get what you suggested, but your suggestion seems to pass the file path to the Run command and open it by a specified filer.  If so, how do I copy the file path on the search result in Wox?

What I want to do is open the path from the query result, which is like "Ctrl + Enter (Open the path of the selected item)" function in the original Everything (and the preferable filer can be specified in the ini file as @smthvitas mentioned).
https://www.voidtools.com/support/everything/keyboard_shortcuts/

I can directly open the path from the search result if I put a folder name in my query, but when I set a file name in my search query, I think I should copy the file path on the search result at first in order to pass it to the Run command.

**Comment by ivangretsky** [comment]
This feature would be so useful! Posting here just to try to move it up on the roadmap))

**Comment by bob-v** [comment]
It would be *awesome* if Wox could do this, it would make it a much more powerful tool, because of all the things you can do in Total Commander (and other commonly used managers), and can't do in Explorer.

**Comment by rickywu** [comment]
没有total commander实在不方便，而且右键菜单也缺少支持
