### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Wox-launcher/Wox#629]
Would be nice to have...

**Comment by bao-qian** [comment]
then you will not be able to auto updates
download the zip from build server,
run it,
you will get error,
change autoupdates to false in `%APPDATA%\Settings\Settings.json`,
run again

**Comment by bao-qian** [comment]
by the way, why you want a portable version?
including settings or not ?

**Comment by Unrepentant-Atheist** [comment]
Because I loathe installers and like to controll what I "install". Don't need autoupdates. I'm quite fine with checking manually.

**Comment by bao-qian** [comment]
<del>sorry, 
by the way, the manually check in about tab is also not working
if you want to use the portable version,
check github release manually</del>
I'm wrong, you can check manually and download manually.

**Comment by ZIEXED** [comment]
I hate installers and I need all the app settings in the same folder
I don't care about auto update featue I don't use it any way and I do check manualy for updates
Please include a Portable version in the releases

**Comment by bao-qian** [comment]
@ZIEXED even I make a portable version in the future, you still need start everything and register it as services.

**Comment by ZIEXED** [comment]
That would be good enough :)

**Comment by tbnguyen1407** [comment]
I personally don't use Everything, just Program plugin. I think the current zip is portable enough, just that the settings are saved to %appdata%.

An option in Wox.exe.config to save settings to current folder would be make it perfectly portable.

**Comment by S-ed** [comment]
Also would like to get a portable app.
I often migrating my apps, and it's a pain to dig the settings inside Users folder.
I guess the simple way is to detect if 'Settings' folder exist inside 'Wox.exe' home folder then Wox will run in portable mode.
By default settings are stored inside:
`%AppData%\Wox\Settings`

**Comment by Starli0n** [comment]
Yes please, I would like a portable version too, for all the same reasons mentioned above.

It is quite easy to implement:
If there is a local config take it, otherwise take the one in `%AppData%\Wox\Settings`.

Thanks

**Comment by alterdaemon** [comment]
I am definitely in favour of portable version.
Lack of portability is the reason that I have not updated my current Wox version (1.2) which is portable.

**Comment by zhizunbao84** [comment]
配置文件夹能否修改位置呢，我不想放在%APPDATA%\Wox，这样重装系统，就全over了

**Comment by alexbde** [comment]
+1

**Comment by ghost** [comment]
i use wox on 3 different computers so it would be good if i could just add a plug-in once and have it sync between computers instead of having to download it manually on each one. same goes for settings.

**Comment by acicovic** [comment]
+1 for a portable version, it is very useful

**Comment by vierlex** [comment]
Hey everyone,

I just came across this app and downloaded the .exe and it installed itself in %appdata%\wox
Came across this thread since I want a portable version too.

But it seems it **already is**, probably not intentionally but functional enough.
You only need to move the wox folder somewhere else and it still works (without creating another "installation" in %appdata% which i thought it might do).

Dont know if that will survive an OS reinstall tough, havent tested that yet :)
I used 1.3.424 for this.

**Comment by starsoccer** [comment]
It is not portable. Every time it starts it makes a folder in roaming/wox

**Comment by seascape** [comment]
My long-time fave Launchy is lagging too much, so I'm looking for a new app launcher. WoX looks like it's among the best, but I was dismayed when I downloaded it, clicked the .exe (wondering if it was an installer or going to unpack itself in the folder) and it proceeded to install itself without even asking where.

The lack of a portable option is a huge negative for my use case, so I probably can't use WoX despite the app itself looking really nice / powerful.

**Comment by davebrny** [comment]
same here. i used wox for a long time but it defeats the purpose of being able to launch things quickly if it takes a few seconds or more to load every time you use it. 
theres plenty of other launchers around these days to choose from but for now ive just gone back to using windows search since its improved a lot over the last few year

you can even make it work more like wox using some autohotkey :D
```autohotkey
#if winActive("ahk_exe SearchUI.exe")

tab::send {down}   ; tab through the search results
+tab::send {up}    ; shift tab

#if
```

or move the search box to the center of the window

```autohotkey
!space::       ; alt + space
send ^{esc}    ; open start menu
winWaitActive, ahk_exe SearchUI.exe, , 1
    {
    winGetPos, , , w, h, ahk_exe SearchUI.exe
    x := (a_screenWidth - w) / 2
    y := (a_screenHeight - h - 200) / 2
    winMove, % x, % y    ; move window to the center

    send {space}{backspace}   ; send a space to show search instead of program list
    }
return
```

**Comment by neatgz** [comment]
stay in Wox v1.2.875, it seems to be the last portable version

**Comment by ghost** [comment]
bump for generic solution

I'm also interested if it will work in restricted access on work PC.

**Comment by Darthagnon** [comment]
EDIT: I've found that the executable can be run from anywhere after I went and extracted it (and dependencies) from the installer executable (you can use https://extract.me/). That's solved my main problem - programs installing to AppData is a big no-no. Unfortunately, it still saves its settings to %APPDATA%; however, as most other programs do so, I might have to live with it, and just follow my standard procedure for backing up something important from AppData: make a hardlink in an already backed-up location. A truly portable version would indeed be nice, though.

Bump. I would love a portable version, too, or at least a version that didn't install itself to %APPDATA%. Means other users on the PC won't get all the Wox plugins I install (the few that aren't broken with the current version, that is).

**Comment by tomasfejfar** [comment]
I have Launchy in my OneDrive so that I don't have to install anything. On a new computer I just log in to OneDrive and I'm done. Launchy is set up to index apps in onedrive, so everything is filled with 🌈 and 🦄 

So, I'd love a protable version, so that I can migrate from Launchy, that seems like an abandonware. Also it completely forgets settings sometimes. 

Having a customisable directory where to store settings would be viable alternative for me as well. I would only install Vox and point it to directory synced in OneDrive.

**Comment by poisonborz** [comment]
+1
Storing user setting sin %Appdata% is just doesn't right for a lot of users. I sync my apps dir between multiple machines, and also want my settings to remain between OS reinstalls.

**Comment by westy** [comment]
As others have said, I like to store my small applications in the cloud, and have them sync down to other machines that need them.

There are workarounds, such as using symlinks, but it's not great.

Wox is a small application, so surely a good fit for being portable!

Cheers

**Comment by ruanimal** [comment]
非常需要，特别我是经常重装系统。。

**Comment by rickywu** [comment]
Where to change the settings path in source?

**Comment by RaymanNg** [comment]
It seems that the config directory is hard coded in Wox.Infrastructure
https://github.com/Wox-launcher/Wox/blob/master/Wox.Infrastructure/Wox.cs

May I just modify above source file to use a relative path to store config data? I wonder whether it will break other codes...

**Comment by RaymanNg** [comment]
Dear maintainers and developers of Wox
I just made a pull request  #2462   for enabling portable mode, would you mind spending some time to take a look and give me some feedback? @jhdxr  
Thanks

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by jjw24** [comment]
Late to the party, but here it is.

Portable mode for current latest version 1.3.524 plus some enhancements:
https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.12.2

Courtesy of the work by @RaymanNg from his PR https://github.com/Wox-launcher/Wox/pull/2462

**Comment by poisonborz** [comment]
Great news! 🎉🎉🎉 Thanks a lot @RaymanNg

**Comment by seascape** [comment]
Thank you, much appreciated. I will evaluate using this software again, now.

Update: For now Wox portable crashes almost immediately (Win10 1607 x64). The tray icon displays briefly. 

The first time I ran Wox it reported that it could not register the alt-space shortcut, presumably because I use that in a similar program. I closed said program, deleted all Wox files, and un-archived it into its folder again. This makes it just go straight to the crash after briefly showing the tray icon.

**Comment by bao-qian** [comment]
Hi guys,

https://github.com/Wox-launcher/Wox/releases

you can Enable portable mode in new release by making a directory named `UserData` along with Wox.exe, or check `Portable Mode` in Settings.

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/81972789-b61d9500-9655-11ea-8f2e-ecbf53ab57df.png)


@Unrepentant-Atheist 
@ZIEXED 
@tbnguyen1407 
@S-ed 
@Starli0n 
@dgutkowsky 
@zhizunbao84 
@alexbde 
@davebrny 
@acicovic 
@vierlex 
@starsoccer 
@seascape 
@neatgz 

@Darthagnon 
@tomasfejfar 
@poisonborz 
@westy 
@ruanima 
@rickywu 
@RaymanNg 
@HsunGong 
@poisonborz 
@seascape
