### ISSUE TITLE
One click to generate report

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#669]
1. include latest logs
2. include squirrel logs 
   1. `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`
   2. `%LOCALAPPDATA%\Wox\SquirrelSetup.log`
3. wox version, os version, installed dlls etc (same as exceptionformater)
4. everything service is running, version of everything (x64 or not).
5. custom python directory, path in `%PATH%`, whether `python.exe` is existed or not.

**Comment by jhdxr** [comment]
what's squirrel log?

**Comment by bao-qian** [comment]
`%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`

**Comment by lances101** [comment]
@happlebao, since Wox is an open sourced project we could take error reporting and handling into the hands of some third parties that provide it for free to such projects. Although I would prefer the error reporting and storing to be on some kind of server that is accessible by Wox staff, I don't think that is possible at this point.

So far I have found 
- [BugSnag](https://bugsnag.com), [C# implementation docs](https://docs.bugsnag.com/platforms/dotnet/wpf/), [OSS free statement](http://blog.bugsnag.com/bugsnag-loves-open-source)
- [Sentry](https://sentry.io/), [C# implementation docs](https://docs.sentry.io/clients/csharp/), [OSS free statement](https://sentry.io/for/open-source/)

The report would be semi-automated, with a dialog allowing the user to send it or not. We could also add a separate prompt after asking the user if he wants to create an issue on GitHub. 

What do you think?
