### ISSUE TITLE
Show most used results first

### ISSUE THREAD

**Issue by enzy** [Wox-launcher/Wox#69]
Remember what item user selected in what query and favor it for future use.

**Comment by qianlifeng** [comment]
Actually, We already added MRU ability for all System plugins. For other third party plugins, like traslation plugins, I'm not sure whether we should remember the user choices since the query is different every time.

@orzFly what's your option? Do we need to give this ability for plugin creaters and let them choose enable it or not? or we enable it for all plugins by default? https://github.com/qianlifeng/Wox/blob/master/Wox/MainWindow.xaml.cs#L426

**Comment by orzFly** [comment]
IMO, there may be some plugins needn't sorting. For example, package
tracking.

I think we should provide a method `MRUSort(List<Result> results)` in
PluginInitContext to let plugins sort results by calling this method.

So plugins can sort only a part results, all results or not.

**Comment by qianlifeng** [comment]
I'm closing this since Wox already remember what item user selected in what query and favor it for future use. checkout UserSelectedRecords.json in your config folder.
