### ISSUE TITLE
[Feature Request] Add setting to clear old input

### ISSUE THREAD

**Issue by Leandros** [Wox-launcher/Wox#804]
If I dismiss Wox with `ESC`, and re-open it, the old input is still in there, and I have to delete it.
Would be great to have a setting to clear the input with each open.

**Comment by bao-qian** [comment]
Did you see that all old texts are selected?

**Comment by Leandros** [comment]
No, they're not selected. I have to either select them, or delete character by character.

**Comment by lances101** [comment]
@Leandros I can add the clearing of the input box as a setting pretty fast, but that would populate the settings menu with more entries that are not all that needed and here is why.  At the current state Wox _should_ select the previous input, so that as soon as you start typing it gets rewritten. Therefore, the functionality you are asking for is already in-built into Wox and I am not sure we should include it (maybe @happlebao has a different opinion though, and then I will add it and PR into the dev branch).

@Leandros Lets try to find out what exactly is happening on your system and why the input is not cleared. Due to how WPF by the .net runtime, sometimes the UI acts differently based on the versions of .net installed. We will try to debug your specific case. 

Easiest way for you to grab the .net versions would be to [use this tool](http://www.asoft-ware.com/download.php?id=11) (you can read more about it[ here](http://www.asoft.be/prod_netver.html)) and paste the log as a comment in this thread. Please, also provide your Windows and Wox versions. Thanks.

**Comment by bao-qian** [comment]
@Leandros your .net version and os version, please.

**Comment by Leandros** [comment]
```
<32Bit>
2.0.50727.8009
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.81.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8009
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.81.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.2  (CLR:4.0)

< Installed Updates >
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Multi-Targeting Pack 
 KB2504637 Update for  (KB2504637)

< Installed Languages 3.0>
German – Germany
English - United States
< Installed Languages 3.5.x>
German – Germany
English - United States
< Installed Languages 4.x>
German – Germany
English - United States
```

Windows 8.1.

I've, just to try, re-installed Wox and it seems to work now.

**Comment by bao-qian** [comment]
close due to issue seems resovled

**Comment by Ciantic** [comment]
This issue still presists 1.3.524.

If I hit esc after typing, and reopen the program, the input is there.

**Comment by Ciantic** [comment]
I found the bug: It occurs only if the checkbox: "Hide Wox when focus is lost" is checked. The clearing works if I remove checkbox from there.

P.S. also, it flashes the old value annoyingly even when I hit esc and return to app (when the checkbox is not checked).
