### ISSUE TITLE
Order items by popularity / Last used

### ISSUE THREAD

**Issue by DagW** [Wox-launcher/Wox#889]
Using version 1.3.183 and loving it.

Order items by recently used
Reproduce:
Install Notepad++
Search for notepad
Windows notepad is on top, launch Notepad++
Search for notepad again
Windows notepad is still on top

**Comment by bao-qian** [comment]
the recent used term will have higher score..
but you need to select it multiple times.. #315

**Comment by DagW** [comment]
OK. I tried multiple times but still no change.
I see now the top selections are shortcuts, do they hive higher priority?
Edit: This seems to be the case, the EXE-file cant seem to get higher priority than the shortcuts?

Personally I dont think shortcuts are needed in the launcher.

**Comment by bao-qian** [comment]
> I see now the top selections are shortcuts, do they hive higher priority?

I think so.

> the EXE-file cant seem to get higher priority than the shortcuts?

not true. if you select this exe file multiple times, it should have higher priority than shortcuts

> Personally I dont think shortcuts are needed in the launcher.

the index of start menu (`C:\ProgramData\Microsoft\Windows\Start Menu\Programs)` are `*.lnk` files (shortcuts)

**Comment by DagW** [comment]
Thanks for answering. 
But if all the executeables are indexed, the shortcurts shouldnt be needed?
Maybe there could be a setting to not show shortcuts? 

Edit
I think I just found this setting, making this a non-issue.
In the Program-plugin, i can choose to remove the ".lnk"-suffix. But it hasnt yet updated, is there a delay?

**Comment by bao-qian** [comment]
> But if all the executeables are indexed, the shortcurts shouldnt be needed?

take wox as a example. 
1. wox is installed into `%LOCALAPPDATA%` because of squirrel auto update framework did that.
and there is no key in `App Paths` in Registry. similar for atoms, slack, vs code etc. so if you didn't search start menu (shortcuts), you can't find them.
2. the link in start menu provide some additional function through `Target` attribute in shortcut. e.g. squirrel auto update framework use it to point to latest application version

> Maybe there could be a setting to not show shortcuts? 

yes, uncheck "Index Start Menu". then click "Reindex".

> But it hasnt yet updated, is there a delay?

click "Reindex".

**Comment by DagW** [comment]
Thanks.
Maybe all I am obsessing about is the arrow on the icon :) maybe there could be a setting to remove that? Anyways..
Love the launcher!
