### ISSUE TITLE
Github icon is not correct

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#936]
![image](https://cloud.githubusercontent.com/assets/1169912/17834283/2a067db8-6731-11e6-9e36-5090c392ce17.png)
![image](https://cloud.githubusercontent.com/assets/1169912/17834284/4673a03e-6731-11e6-8b45-fc9b48193c36.png)
but same code is running correctly in a new vs solution.

``` csharp
var path = @"C:\Users\Ricky\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\GitHub.appref-ms";
var shfi = new SHFILEINFO();
var himl = SHGetFileInfo(
    path,
    FILE_ATTRIBUTE_NORMAL,
    ref shfi,
    (uint)Marshal.SizeOf(shfi),
    SHGFI_SYSICONINDEX
);
var hIcon = ImageList_GetIcon(himl, shfi.iIcon, ILD_NORMAL);
var img = Imaging.CreateBitmapSourceFromHIcon(
    hIcon,
    Int32Rect.Empty,
    BitmapSizeOptions.FromEmptyOptions()
);
DestroyIcon(hIcon);

[DllImport("User32.dll")]
private static extern int DestroyIcon(IntPtr hIcon);
[DllImport("Shell32.dll", CharSet = CharSet.Unicode)]
private static extern IntPtr SHGetFileInfo(string pszPath, uint dwFileAttributes, ref SHFILEINFO psfi, uint cbFileInfo, uint uFlags);
[DllImport("comctl32.dll")]
private static extern IntPtr ImageList_GetIcon(IntPtr himl, int i, uint flags);
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
private struct SHFILEINFO
{
    readonly IntPtr hIcon;
    internal readonly int iIcon;
    readonly uint dwAttributes;
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = MAX_PATH)]
    readonly string szDisplayName;
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = NAMESIZE)]
    readonly string szTypeName;
}
private const int NAMESIZE = 80;
private const int MAX_PATH = 256;
private const uint SHGFI_SYSICONINDEX = 0x000004000; // get system icon index
private const uint FILE_ATTRIBUTE_NORMAL = 0x00000080;
private const uint ILD_NORMAL = 0x00000000;
```

**Comment by huseyint** [comment]
I think I have found out why this call on Wox project returns an empty/blank/default file icon, it is due to the calling thread's ApartmentState which is MTA. Please read more about it here:

http://stackoverflow.com/a/31931554/39

I can confirm that making this thread a STA thread will load the correct icon successfully on Wox project. Or you can also reproduce the issue on a new WPF project by modifying the above sample code to use a MTA (by default threads are MTA) thread while performing the SHGetFileInfo call.

As far as I can see, 2 areas need to be updated to make this icon work on Wox project:

1. `ImageLoader.Initialize` call which uses `AsParallel()` PLINQ extension method that creates MTA threads. There is a `StaTaskScheduler` implementation over at [MSDN](https://code.msdn.microsoft.com/ParExtSamples) but `AsParallel()` does not support custom TaskSchedulers. I have a quick fix for this though, I have used `Parallel.ForEach()` method with a `ParallelOptions` pointing to a `StaTaskScheduler` instance. This fixed the icon if it is loaded during initialization of the app.
2. `ResultViewModel.Image` property is bound from XAML code with `IsAsync=True` attribute, therefor the framework calls this getter on a separate MTA thread. I am not sure if it is possible to tell the framework to create a STA thread rather than a MTA thread while calling this property getter.

**Comment by bao-qian** [comment]
Excellent! I will take a detail look tomorrow.

**Comment by bao-qian** [comment]
fixed in this pr https://github.com/Wox-launcher/Wox/pull/2849
by using new mordern api https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitemimagefactory-getimage
