### ISSUE TITLE
Win+R crash on "php -v"

### ISSUE THREAD

**Issue by metude** [Wox-launcher/Wox#95]
My wox configuration replaces with `Win+R` but it crashes on `php -v`.

**Comment by qianlifeng** [comment]
Could you put more details about the crash info?

**Comment by metude** [comment]
How can I get crash info?

**Comment by qianlifeng** [comment]
@metude check the log.txt in your wox directory.

**Comment by thecotne** [comment]
@qianlifeng you should make wiki page about how to report bug and first thing to do is to check log.txt

**Comment by qianlifeng** [comment]
@thecotne I will add it. 

I know there are lots of wiki staff we need to do, like how to build a python plugin with the new plugin system. Also function guide is necessary, since some system plugin in our setting dialog is not easy enough to understood for users. Hope someone can contribute some wikis :smile:

**Comment by orzFly** [comment]
I think you can add lines from “log.txt” to the crash report generated by my code too. 
-- 
orzFly / Yeechan Lu

On July 22, 2014 at 15:11:40, qianlifeng (notifications@github.com) wrote:

@thecotne I will add it.

I know there are lots of wiki staff we need to do, like how to build a python plugin with the new plugin system. Also function guide is necessary, since some system plugin in our setting dialog is not easy enough to understood for users. Hope someone can contribute some wikis

**Comment by metude** [comment]
```
Date:2014-07-22 19:33:59,361 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
```

I tried second time, now it works but cmd windows close itself immediatly.

**Comment by thecotne** [comment]
@qianlifeng i think it's same issue that i had #117

**Comment by qianlifeng** [comment]
Wox has now packed python envionment, so `Could't find python environment` issue should not be exist.

**Comment by metude** [comment]
I was using previous version, I updated wox, issue still remains. But there's no crash log. Actually, wox doesn't crash in new version, but `php -v` should open cmd and show version of php. CMD window closes itself immediatly.

**Comment by roose** [comment]
@metude is normal behavior for cmd in windows
@qianlifeng I think could be add option to run cmd with parameter /K ([/k : Carries out the command specified by string and continues.](http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/cmd.mspx?mfr=true))

**Comment by metude** [comment]
@roose Normal behavior for cmd doesn't mean expected behavior. 
Thanks for pointing out source of issue.

**Comment by roose** [comment]
@qianlifeng sorry for my unobservant =)
@metude in settings, Shell plugin, check: "Do not close prompt after execution"
