### ISSUE TITLE
System.NotSupportedException 

### ISSUE THREAD

**Issue by vlrmprjct** [Wox-launcher/Wox#955]
Unknown ModifierKeys-Element "STRG".
Wox crashes after start.

[2016-08-31.txt](https://github.com/Wox-launcher/Wox/files/448140/2016-08-31.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 08/31/2016 21:46:41
Exception:
WindowsBase
System.NotSupportedException
Unbekanntes ModifierKeys-Element "STRG".
   bei System.Windows.Input.ModifierKeysConverter.GetModifierKeys(String modifiersToken, CultureInfo culture)
   bei System.Windows.Input.ModifierKeysConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   bei System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   bei System.Windows.Input.KeyGesture.CreateFromResourceStrings(String keyGestureToken, String keyDisplayString)
   bei MS.Internal.Commands.CommandHelpers.RegisterCommandHandler(Type controlType, RoutedCommand command, ExecutedRoutedEventHandler executedRoutedEventHandler, CanExecuteRoutedEventHandler canExecuteRoutedEventHandler, String srid1, String srid2)
   bei System.Windows.Documents.TextEditorSelection._RegisterClassHandlers(Type controlType, Boolean registerEventListeners)
   bei System.Windows.Documents.TextEditor.RegisterCommandHandlers(Type controlType, Boolean acceptsRichContent, Boolean readOnly, Boolean registerEventListeners)
   bei System.Windows.Controls.RichTextBox..ctor(FlowDocument document)
   bei System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlType_RichTextBox>b__923_0()
   bei System.Windows.Baml2006.WpfKnownTypeInvoker.CreateInstance(Object[] arguments)
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)

**Comment by bao-qian** [comment]
so you can't start wox now?

**Comment by vlrmprjct** [comment]
Correct. Steps: Install Wox, after finishing install it crashes with the error message above. Kill the running process , start again, crash again. Deleting the %Appdata% will not fix the issue.

**Comment by bao-qian** [comment]
> Deleting the %Appdata% will not fix the issue.

are you sure you deleted `%APPDATA%\Wox` ?

**Comment by vlrmprjct** [comment]
Yes, i'm sure.

Running Wox on my other machine and i love it, 
but don't know what the difference is between these machines.

**Comment by lances101** [comment]
This looks like an issue with the german locale -  https://connect.microsoft.com/VisualStudio/feedback/details/2455692/system-notsupportedexception-unbekanntes-modifierkeys-element-strg-when-loading-wpf-application-on-net-460267

This issue should've been fixed with Windows's build `14295` and you are running `14393` so you should be alright. It's difficult to come with a upright fix, this is an issue with the framework itself :(

**Comment by vlrmprjct** [comment]
Thanks.
So, maybe, i have to wait for a (MS) fix ?

**Comment by bao-qian** [comment]
> Posted by Sachin [MSFT] on 6/23/2016 at 5:32 PM
> The WPF team has reviewed this issue and found this does not repro latest build of Windows 10 with .NET. We thank you for the feedback and consider this issue closed   – WPF team

try upgrade to windows 10 anniversary update

**Comment by vlrmprjct** [comment]
This is the Win10 Dev Build. 
There is no way to upgrade.

**Comment by lances101** [comment]
@telekommander what do you mean by Dev build? Like an insider preview?
I've done some research and confirmed once again that the "STRG" issue happens only on german locale on older versions of Win 10. WPF is not interpreting STRG as CTRL and there is sadly nothing we can do to fix it for you without implementing a dirty hack. Your only option would be to upgrade your system. 

In theory, you should have issues with other WPF applications that use keybindings too, since that is where the actual problem is. 

@happlebao, this one will most likely end up being labeled as "wont-fix".
